import { defineField, defineType } from "sanity";

export const productSchema = defineType({
  name: "product",
  title: "Product",
  type: "document",
  groups: [
    { name: "info", title: "Product Info", default: true },
    { name: "specs", title: "Specifications" },
    { name: "export", title: "Export & Packaging" },
    { name: "media", title: "Media & Downloads" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "name",
      title: "Product Name (English)",
      type: "string",
      group: "info",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "nameTr",
      title: "Product Name (Turkish)",
      type: "string",
      group: "info",
    }),
    defineField({
      name: "nameAr",
      title: "Product Name (Arabic)",
      type: "string",
      group: "info",
    }),
    defineField({
      name: "slug",
      title: "URL Slug",
      type: "slug",
      group: "info",
      options: { source: "name" },
      validation: (r) => r.required(),
    }),
    defineField({
      name: "category",
      title: "Product Category",
      type: "reference",
      to: [{ type: "productCategory" }],
      group: "info",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "summary",
      title: "Short Summary (100–120 words)",
      type: "text",
      rows: 4,
      group: "info",
    }),
    defineField({
      name: "description",
      title: "Full Technical Description",
      type: "array",
      of: [{ type: "block" }],
      group: "info",
    }),
    defineField({
      name: "viscosityGrade",
      title: "SAE Viscosity Grade",
      type: "string",
      group: "specs",
      placeholder: "e.g. 15W-40",
    }),
    defineField({
      name: "apiClassification",
      title: "API Classification",
      type: "string",
      group: "specs",
      placeholder: "e.g. CI-4/SL",
    }),
    defineField({
      name: "aceaClassification",
      title: "ACEA Classification",
      type: "string",
      group: "specs",
      placeholder: "e.g. E7, A3/B4",
    }),
    defineField({
      name: "specifications",
      title: "Technical Specifications",
      type: "array",
      group: "specs",
      of: [
        {
          type: "object",
          fields: [
            { name: "property", title: "Property", type: "string" },
            { name: "value", title: "Value", type: "string" },
            { name: "testMethod", title: "Test Method (e.g. ASTM D445)", type: "string" },
          ],
          preview: {
            select: { title: "property", subtitle: "value" },
          },
        },
      ],
    }),
    defineField({
      name: "applications",
      title: "Applications",
      type: "array",
      group: "specs",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "oemApprovals",
      title: "OEM Approvals",
      type: "array",
      group: "specs",
      of: [
        {
          type: "object",
          fields: [
            { name: "oem", title: "OEM (e.g. Mercedes-Benz)", type: "string" },
            { name: "spec", title: "Specification (e.g. MB 228.3)", type: "string" },
            { name: "status", title: "Status", type: "string", options: { list: ["Approved", "Meets Requirements", "Recommended"] } },
          ],
          preview: { select: { title: "oem", subtitle: "spec" } },
        },
      ],
    }),
    defineField({
      name: "certifications",
      title: "Certifications",
      type: "array",
      group: "specs",
      of: [{ type: "reference", to: [{ type: "certification" }] }],
    }),
    defineField({
      name: "packagingOptions",
      title: "Packaging Options",
      type: "array",
      group: "export",
      of: [
        {
          type: "object",
          fields: [
            { name: "type", title: "Package Type", type: "string", options: { list: ["20L Pail", "205L Drum", "1000L IBC", "Bulk Tanker"] } },
            { name: "capacity", title: "Capacity", type: "string" },
            { name: "unitsPerPallet", title: "Units per Pallet", type: "string" },
            { name: "grossWeight", title: "Gross Weight", type: "string" },
          ],
          preview: { select: { title: "type", subtitle: "capacity" } },
        },
      ],
    }),
    defineField({
      name: "heroImage",
      title: "Hero Image",
      type: "image",
      group: "media",
      options: { hotspot: true },
      fields: [{ name: "alt", title: "Alt Text", type: "string" }],
    }),
    defineField({
      name: "galleryImages",
      title: "Gallery Images",
      type: "array",
      group: "media",
      of: [{ type: "image", options: { hotspot: true }, fields: [{ name: "alt", type: "string" }] }],
    }),
    defineField({
      name: "technicalDataSheet",
      title: "Technical Data Sheet (TDS) PDF",
      type: "file",
      group: "media",
      options: { accept: ".pdf" },
    }),
    defineField({
      name: "safetyDataSheet",
      title: "Safety Data Sheet (SDS/MSDS) PDF",
      type: "file",
      group: "media",
      options: { accept: ".pdf" },
    }),
    defineField({
      name: "inStock",
      title: "In Stock",
      type: "boolean",
      group: "info",
      initialValue: true,
    }),
    defineField({
      name: "featuredOrder",
      title: "Featured Order (lower = first on homepage)",
      type: "number",
      group: "info",
    }),
    defineField({
      name: "metaTitle",
      title: "Meta Title",
      type: "string",
      group: "seo",
    }),
    defineField({
      name: "metaDescription",
      title: "Meta Description",
      type: "text",
      rows: 3,
      group: "seo",
    }),
  ],
  preview: {
    select: { title: "name", subtitle: "viscosityGrade", media: "heroImage" },
  },
});
