import json

with open('c:/dev/model-oils/messages/tr.json', encoding='utf-8') as f:
    tr = json.load(f)

sol = tr['solutions']

sol['breadcrumbHome'] = 'Ana Sayfa'
sol['breadcrumbSolutions'] = 'Çözümler'
sol['requestQuote'] = 'Teklif İste'
sol['browseCatalog'] = 'Ürün Kataloğunu İncele'
sol['challengesTitle'] = 'Çözdüğümüz Yaygın Sorunlar'
sol['solutionsTitle'] = 'Model Oils Bunları Nasıl Çözüyor'
sol['recommendedTitle'] = '{title} İçin Önerilen Ürünler'
sol['viewFullCatalog'] = 'Tam Ürün Kataloğunu Gör'
sol['faqTitle'] = 'Sıkça Sorulan Sorular'
sol['ctaTitle'] = 'Gereksinimlerinizi Görüşmeye Hazır mısınız?'
sol['ctaBody'] = 'İhracat ekibimiz fiyatlandırma, teknik özellikler ve belgelerle 24 saat içinde yanıt verir.'
sol['ctaBtn'] = 'Teklif İste'

fleet = sol['fleet']
fleet['title'] = 'Filo Operatörleri'
fleet['eyebrow'] = 'Filo Operatörleri İçin Çözümler'
fleet['headline'] = 'Ticari Filolar İçin Tutarlı Motor Yağı Temini'
fleet['subheadline'] = 'Birden fazla yağ tedarikçisini yönetmeyi bırakın. Dizel ve benzinli filolar için dökme SAE motor yağları tedarik ediyoruz.'
fleet['p1'] = 'Erken yağ değişim aralıklarına neden olan tutarsız kalite'
fleet['p2'] = 'Uyumsuz teknik özelliklerle birden fazla tedarikçi'
fleet['p3'] = 'Premium perakende yağlardan artan bakım maliyetleri'
fleet['p4'] = 'OEM garanti programlarından belgeleme gereksinimleri'
fleet['p5'] = 'Yeniden sipariş koordinasyonu için özel hesap yöneticisi yok'
fleet['s1t'] = 'Filonuzla Ölçeklenen Toplu Fiyatlandırma'
fleet['s1d'] = '1.000 litrelik deneme siparişlerinden dökme tankere. IBC ve tanker hacimlerinde litre başına fiyat önemli ölçüde düşer.'
fleet['s2t'] = 'API ve OEM Teknik Özellik Eşleştirme'
fleet['s2d'] = 'Teknik ekibimiz filonuzun OEM gereksinimlerine göre doğru API SN, CJ-4 veya CK-4 teknik özelliğini belirler.'
fleet['s3t'] = 'Partiden Partiye Tutarlı Kalite'
fleet['s3d'] = 'Her siparişte ISO 9001:2015 kalite yönetimi ve parti bazlı COA. Aynı formülasyon, aynı performans.'
fleet['s4t'] = 'Esnek Teslimat Planlaması'
fleet['s4d'] = 'Aylık, üç aylık veya yıllık tedarik anlaşmaları. Proaktif temin süresi bildirimi.'
fleet['testimonial'] = "200 araçlık filomuz için üç ayrı yerel tedarikçiden Model Oils'e geçtik. Fiyatlandırma ve belgeler iyileşti, 18 aydır uyumsuzluk yaşamadık."
fleet['testimonialName'] = 'Kwame A.'
fleet['testimonialRole'] = 'Filo Bakım Direktörü, Batı Afrika'
fleet['faq1q'] = 'Filo tedariki için minimum sipariş nedir?'
fleet['faq1a'] = 'Minimum 1.000 litredir. Tedarik anlaşması yapmadan önce deneme siparişiyle başlamanızı öneririz.'
fleet['faq2q'] = 'Modern dizel motorlar için API CK-4 sertifikalı yağ tedarik edebilir misiniz?'
fleet['faq2a'] = 'Evet. SAE 15W-40 HD dizel yağımız API CK-4 sertifikalıdır. Her sevkiyatla COA sağlanır.'
fleet['faq3q'] = 'Fiyat sabitleme anlaşmaları sunuyor musunuz?'
fleet['faq3a'] = 'Evet. Minimum üç aylık hacme taahhüt eden doğrulanmış filo operatörleri için 6 ve 12 aylık fiyat sabitleme anlaşmaları mevcuttur.'
fleet['faq4q'] = 'Tek sevkiyatta birden fazla teknik özellik için ürünleri karıştırabilir miyim?'
fleet['faq4a'] = 'Evet. Her parti için ayrı COA ile tek konteyner içinde çok ürünlü siparişleri düzenli olarak sevk ediyoruz.'

dist = sol['distributors']
dist['title'] = 'Otomotiv Distribütörleri'
dist['eyebrow'] = 'Otomotiv Distribütörleri İçin Çözümler'
dist['headline'] = 'Distribütörler İçin Güvenilir Toplu Motor Yağı Temini'
dist['subheadline'] = 'Dağıtım ağınız için API ve ACEA sertifikalı motor yağlarının tutarlı tedarikini sağlayın. Özel etiket ve birlikte paketleme mevcuttur.'
dist['p1'] = 'Stok boşluklarına neden olan güvenilmez tedarikçi'
dist['p2'] = 'Mevcut üreticiden özel etiket seçeneği yok'
dist['p3'] = 'Otomotiv sektörü alıcılarının API ve ACEA sertifikaları gerektirmesi'
dist['p4'] = 'Son müşterilerden tutarsız kalite şikayetleri'
dist['p5'] = 'Birden fazla kaynak tedarikçi sürdürmenin yüksek maliyeti'
dist['s1t'] = 'Özel Etiket ve Birlikte Paketleme'
dist['s1d'] = "Etiketinizle, varil ve IBC'lerde markanızın baskısıyla ürün tedarik edebiliriz. Minimum 5.000 litre."
dist['s2t'] = 'Tam API ve ACEA Sertifika Portföyü'
dist['s2d'] = 'Motor yağı serimizde API SN, SN+, CF, CK-4 ve ACEA A3/B4, C3, E7, E9.'
dist['s3t'] = 'Distribütör Fiyat Kademeleri'
dist['s3d'] = 'Üç aylık minimum siparişe taahhüt eden distribütörler için ek marjla hacim bazlı fiyatlandırma.'
dist['s4t'] = 'Eksiksiz İhracat Belgeleme'
dist['s4d'] = 'COA, MSDS, Menşe Şahadetnamesi ve ülkeye özel uyumluluk belgeleri dahil.'
dist['testimonial'] = "Tüm ürün serimizi 14 ay önce Model Oils'e taşıdık. Özel etiket kurulumu basitti ve API belgeleri yerel ticaret otoritesi gereksinimlerini anında karşıladı."
dist['testimonialName'] = 'Rodrigo M.'
dist['testimonialRole'] = 'İthalat Direktörü, Güney Amerika'
dist['faq1q'] = 'Özel etiket üretimi için minimum nedir?'
dist['faq1a'] = 'SKU başına 5.000 litredir. Etiket baskı onayından sevkiyata 10–14 iş günü.'
dist['faq2q'] = 'Avrupa binek araç dağıtımı için ACEA A3/B4 tedarik edebilir misiniz?'
dist['faq2a'] = 'Evet. 5W-30 ve 5W-40 sentetik yağlarımız ACEA A3/B4 ve C3 için test edilmiştir.'
dist['faq3q'] = 'Münhasır distribütörlük anlaşmalarıyla çalışıyor musunuz?'
dist['faq3a'] = 'Evet, seçili pazarlarda. Minimum yıllık hacim taahhüdü gerekir, üç ayda bir gözden geçirilir.'
dist['faq4q'] = 'Son müşterilerimin kalite şikayetlerini nasıl ele alıyorsunuz?'
dist['faq4a'] = 'COA parti numaraları aracılığıyla tüm partiler izlenebilir. 48 saat içinde inceliyoruz ve yazılı yanıt veriyoruz.'

ind = sol['industrial']
ind['title'] = 'Endüstriyel Şirketler'
ind['eyebrow'] = 'Endüstriyel Şirketler İçin Çözümler'
ind['headline'] = 'Üretim ve İşleme Tesisleri İçin Endüstriyel Yağlayıcılar'
ind['subheadline'] = 'Endüstriyel makineler için hidrolik sıvılar, dişli yağları, kompresör yağları ve özel yağlayıcılar. ISO VG sınıflandırmalı, OEM teknik özelliği eşleştirilmiş.'
ind['p1'] = 'Birden fazla tedarikçiden birden fazla yağlayıcı türü — tedarik karmaşıklığı'
ind['p2'] = "Büyük OEM'lerden yüksek litre başına maliyet"
ind['p3'] = 'Yerel distribütörlerin stoklamadığı ISO VG sınıflarını tedarik etme zorluğu'
ind['p4'] = 'Garanti uyumluluğu için OEM onay belgeleme ihtiyacı'
ind['p5'] = 'Planlanmamış üretim duruşlarına neden olan tutarsız temin süreleri'
ind['s1t'] = 'Tek Tedarikçi Altında Tam Endüstriyel Yağlayıcı Yelpazesi'
ind['s1d'] = 'Hidrolik yağlar (ISO VG 32/46/68/100), dişli yağları (GL-4/GL-5), kompresör yağları, gresler ve metal işleme sıvıları.'
ind['s2t'] = 'ISO VG Sınıf Eşleştirme'
ind['s2d'] = 'DIN 51524, ISO 6743 veya üretici teknik özelliğine uygun herhangi bir ISO VG sınıfını stokluyor veya formüle edebiliyoruz.'
ind['s3t'] = 'Uzun Vadeli Tedarik Anlaşmaları'
ind['s3d'] = 'Üç aylık teslimat planlamalı yıllık tedarik anlaşmaları. Tutarlı fiyatlandırma, tutarlı teknik özellik, özel hesap yöneticisi.'
ind['s4t'] = 'Teknik Uzmanlık'
ind['s4d'] = 'Mühendislerimiz mevcut ürün listenizi inceleyerek konsolidasyon fırsatlarını belirleyebilir.'
ind['testimonial'] = 'Yedi ayrı yağlayıcı tedarikçisini ikiye indirdik. Maliyet düşüşü önemli oldu ve teknik destek mükemmeldi.'
ind['testimonialName'] = 'Dmitri K.'
ind['testimonialRole'] = 'Satın Alma Müdürü, Doğu Avrupa Üretim Grubu'
ind['faq1q'] = 'ISO 6743 sınıflandırmasına göre yağlayıcı tedarik ediyor musunuz?'
ind['faq1a'] = 'Evet. HLP hidrolik sıvılar, CKD dişli yağları, VDL kompresör yağları dahil ISO 6743 kategorilerini kapsıyoruz.'
ind['faq2q'] = "Büyük OEM yağlayıcı teknik özelliklerine göre çapraz referans yapabilir misiniz?"
ind['faq2a'] = "Evet. Bosch Rexroth, Parker ve diğer büyük hidrolik OEM'lere karşı çapraz referans tabloları tutuyoruz."
ind['faq3q'] = 'Endüstriyel yağlayıcılar için temin süresi nedir?'
ind['faq3a'] = 'Standart sınıflar stoktan 5–10 iş günüdür. Özel ISO VG sınıflar 15–20 iş günü gerektirir.'
ind['faq4q'] = 'Yağlayıcı denetim hizmeti sunuyor musunuz?'
ind['faq4a'] = 'Evet. Tedarik anlaşması değerlendiren nitelikli alıcılar için ücretsiz portföy değerlendirmesi sunuyoruz.'

imp = sol['importers']
imp['title'] = 'Yağlayıcı İthalatçıları'
imp['eyebrow'] = 'Yağlayıcı İthalatçıları İçin Çözümler'
imp['headline'] = 'Yağlayıcı İthalatçıları İçin Güvenilir Türk İhracat Ortağı'
imp['subheadline'] = '15 yılı aşkın uluslararası ticaret deneyimiyle İstanbul merkezli yağlayıcı ihracatçısı. Tutarlı kalite, rekabetçi FOB/CIF fiyatlandırması, eksiksiz gümrük belgeleme.'
imp['p1'] = 'İhracat belgelemesini de üstlenen güvenilir üretici bulmada zorluk'
imp['p2'] = 'Ticaret şirketlerinden partiler arasında kalite tutarsızlığı'
imp['p3'] = 'Karmaşık ithalat uyumluluk belgeleme gereksinimleri'
imp['p4'] = 'Büyük yağlayıcı markalarının yüksek minimum sipariş miktarları'
imp['p5'] = 'Incoterms ve ödeme koşullarında sınırlı esneklik'
imp['s1t'] = 'Ticaret Şirketi Değil, Doğrudan Üretici'
imp['s1d'] = 'Yağlayıcıları İstanbul tesisimizde harmanlar ve paketleriz. Aracı yok, marj ekleme yok.'
imp['s2t'] = 'Bünyede Eksiksiz İhracat Belgeleme'
imp['s2d'] = 'Özel ticaret uyum ekibimiz ithalat gümrüğü için gereken her belgeyi hazırlar.'
imp['s3t'] = 'Esnek Incoterms ve Ödeme Koşulları'
imp['s3d'] = 'EXW, FOB, CFR, CIF, DAP veya DDP. T/T veya görüldüğünde Akreditif.'
imp['s4t'] = 'Özel İhracat Hesap Yöneticisi'
imp['s4d'] = 'Sipariş onayından varış limanında teslimata kadar tek iletişim noktası.'
imp['testimonial'] = 'Üç farklı ülkede gümrük işlemlerini yöneten bir ithalatçı olarak belge doğruluğu kritik. Model Oils 18 ayda 23 sevkiyatta tek hata yapmadı.'
imp['testimonialName'] = 'Priya N.'
imp['testimonialRole'] = 'İthalat ve Lojistik Müdürü, Güneydoğu Asya'
imp['faq1q'] = 'Üretici misiniz yoksa ticaret şirketi mi?'
imp['faq1a'] = "Üretici ve ihracatçıyız. Tüm harmanlamanın ve paketlemenin yapıldığı yer İstanbul tesisimizdir."
imp['faq2q'] = 'Tipik temin süreleriniz nedir?'
imp['faq2a'] = 'Standart stok ürünleri: proforma onayından 5–7 iş günü. Özel formülasyonlar: 15–20 iş günü.'
imp['faq3q'] = 'Belirli ülke ithalat gereksinimleri için belgeleme hazırlayabilir misiniz?'
imp['faq3a'] = "Evet. 40'tan fazla ülkeye ihracat deneyimimiz var ve ülkeye özel gereksinimleri güncel tutuyoruz."
imp['faq4q'] = 'Ülkemizde mevcut bir ithalatçınız var mı?'
imp['faq4a'] = "Çoğu pazarda doğrudan ithalatçılarla çalışıyoruz. Münhasırlık anlaşmaları minimum yıllık hacim taahhüdü ile mevcuttur."

tr['solutions'] = sol
with open('c:/dev/model-oils/messages/tr.json', 'w', encoding='utf-8') as f:
    json.dump(tr, f, ensure_ascii=False, indent=2)
print('Done. fleet title:', tr['solutions']['fleet']['title'])
print('importers title:', tr['solutions']['importers']['title'])
