"""
Patches messages/en.json, tr.json, ru.json, fa.json with pd namespace entries
for all 62 Shell industrial products. No API key required — translations embedded.
"""
import json, os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MSG  = os.path.join(BASE, "messages")

# ── Turkish (from source JSON) ───────────────────────────────────────────────

def load_tr():
    scripts = os.path.join(BASE, "scripts")
    all_products = {}
    for i in [1, 2, 3]:
        with open(os.path.join(scripts, f"ind_part{i}.json"), encoding="utf-8") as f:
            all_products.update(json.load(f))
    result = {}
    for slug, p in all_products.items():
        feats = p["features"]
        result[slug] = {
            "type": p["type"],
            "description": p["description"],
            "f0": feats[0] if len(feats) > 0 else "",
            "f1": feats[1] if len(feats) > 1 else "",
            "f2": feats[2] if len(feats) > 2 else "",
            "f3": feats[3] if len(feats) > 3 else "",
        }
    return result

# ── English ──────────────────────────────────────────────────────────────────

EN = {
  "tellus-s2-m-32": {"type":"Hydraulic Oil","description":"High-performance ISO 11158 HM hydraulic oil. Exceptional thermal stability, outstanding oxidation resistance and anti-wear protection for industrial hydraulic systems.","f0":"Thermal stability","f1":"Oxidation resistance","f2":"Anti-wear protection","f3":"Excellent filterability"},
  "tellus-s2-m-46": {"type":"Hydraulic Oil","description":"High-performance ISO 11158 HM hydraulic oil for the most widely used viscosity grade. Superior thermal stability, oxidation resistance and anti-wear protection.","f0":"Thermal stability","f1":"Outstanding anti-wear protection","f2":"Excellent filterability","f3":"Water separation"},
  "tellus-s2-m-68": {"type":"Hydraulic Oil","description":"High-performance ISO 11158 HM hydraulic oil for high-temperature and heavy-duty applications. Superior thermal stability and outstanding anti-wear protection.","f0":"High temperature stability","f1":"Outstanding anti-wear protection","f2":"Excellent filterability","f3":"Water separation"},
  "tellus-s2-m-100": {"type":"Hydraulic Oil","description":"High-viscosity ISO 11158 HM hydraulic oil. Superior protection for vacuum pumps and high-pressure hydraulic systems.","f0":"High viscosity stability","f1":"Oxidation resistance","f2":"Anti-wear protection","f3":"Water separation"},
  "tellus-s2-v-15": {"type":"High VI Hydraulic Oil","description":"High VI hydraulic oil with stable viscosity across a wide temperature range. Ideal for cold environments and precision control systems.","f0":"High viscosity index","f1":"Wide temperature range","f2":"Thermal stability","f3":"Excellent filterability"},
  "tellus-s2-v-22": {"type":"High VI Hydraulic Oil","description":"High VI hydraulic oil providing consistent viscosity across a wide temperature range. Suitable for industrial and mobile hydraulic systems in variable temperature conditions.","f0":"High viscosity index","f1":"Wide temperature performance","f2":"Anti-wear protection","f3":"Oxidation resistance"},
  "tellus-s2-v-32": {"type":"High VI Hydraulic Oil","description":"Hydraulic oil with high viscosity index for consistent performance across a wide temperature range. Suitable for outdoor machinery and mobile systems.","f0":"High VI","f1":"Wide temperature range","f2":"Denison HF-0 approved","f3":"Water separation"},
  "tellus-s2-v-46": {"type":"High VI Hydraulic Oil","description":"High VI formulation for the most common hydraulic viscosity grade. Outstanding pump protection and consistent performance in both industrial and mobile systems.","f0":"High viscosity index","f1":"Most common hydraulic viscosity","f2":"Superior pump protection","f3":"Excellent filterability"},
  "tellus-s2-v-68": {"type":"High VI Hydraulic Oil","description":"High VI hydraulic oil for high-temperature, heavy-duty systems. Reliable performance in construction and mining equipment.","f0":"High temperature stability","f1":"Heavy-duty compatible","f2":"High viscosity index","f3":"Anti-wear protection"},
  "tellus-s2-v-100": {"type":"High VI Hydraulic Oil","description":"High VI hydraulic oil for large hydraulic systems requiring extra load capacity. Stable viscosity in slow-running large systems.","f0":"Extra load capacity","f1":"High VI","f2":"Large system compatible","f3":"Thermal stability"},
  "tellus-s3-m-32": {"type":"Ashless Hydraulic Oil","description":"Zinc-free ashless hydraulic oil. Ideal for sensitive servo valves and systems containing silver or magnesium alloy components.","f0":"Zinc-free formula","f1":"Servo valve compatible","f2":"Fine filter compatible","f3":"Wide system compatibility"},
  "tellus-s3-m-46": {"type":"Ashless Hydraulic Oil","description":"Zinc-free ashless hydraulic oil protecting sensitive servo valves and alloy components. The most common industrial viscosity grade.","f0":"Ashless formula","f1":"Servo valve compatible","f2":"Superior oxidation stability","f3":"Fine filter compatible"},
  "tellus-s3-m-68": {"type":"Ashless Hydraulic Oil","description":"Zinc-free ashless hydraulic oil for high-temperature, heavy-load conditions. Suitable for industrial presses and construction equipment.","f0":"Zinc-free formula","f1":"High temperature stability","f2":"Heavy load capacity","f3":"Anti-wear protection"},
  "tellus-s3-m-100": {"type":"Ashless Hydraulic Oil","description":"Zinc-free ashless formulation offering superior protection for high-viscosity, large hydraulic systems. Ideal for heavy presses and industrial facilities.","f0":"Zinc-free formula","f1":"Extra load capacity","f2":"Large system compatible","f3":"Extended service intervals"},
  "tellus-s4-me-32": {"type":"Energy-Saving Hydraulic Oil","description":"Energy-saving synthetic technology hydraulic oil. Advanced formulation increases system efficiency while providing extended oil life.","f0":"Energy saving","f1":"Synthetic technology","f2":"Extended oil life","f3":"Superior oxidation resistance"},
  "tellus-s4-me-46": {"type":"Energy-Saving Hydraulic Oil","description":"Energy-saving synthetic technology hydraulic oil for the most common viscosity grade. Enhances system efficiency and extends oil drain intervals.","f0":"Energy saving","f1":"Synthetic technology","f2":"Extended drain interval","f3":"Superior anti-wear protection"},
  "tellus-s4-vx-32": {"type":"Wide Temperature Range Hydraulic Oil","description":"Synthetic technology hydraulic oil providing stable viscosity across an extremely wide temperature range. Superior performance from arctic conditions to high temperatures.","f0":"Very wide temperature range","f1":"Synthetic technology","f2":"High viscosity index","f3":"Cold start advantage"},
  "morlina-s2-bl-5": {"type":"Circulation / Turbine Oil","description":"Zinc-free ultra-low viscosity circulation oil. Ideal for high-speed bearings and precision circulation systems, with a -60°C pour point for cold environments.","f0":"Zinc-free formula","f1":"Ultra-low viscosity","f2":"Pour point -60°C","f3":"Oxidation resistance"},
  "morlina-s2-bl-10": {"type":"Circulation / Turbine Oil","description":"Zinc-free low-viscosity circulation oil. Superior oxidation stability for steam turbines, gas turbines and high-speed circulation systems.","f0":"Turbine-grade water separation","f1":"Long oxidation life","f2":"Siemens and GE approved","f3":"Foam inhibiting"},
  "morlina-s2-bl-22": {"type":"Circulation / Turbine Oil","description":"Zinc-free ISO VG 22 circulation oil. High oxidation resistance and corrosion protection for plain and rolling element bearings and precision circulation systems.","f0":"Zinc-free formula","f1":"High oxidation resistance","f2":"Corrosion protection","f3":"Low foam tendency"},
  "morlina-s2-b-46": {"type":"Circulation / Bearing Oil","description":"Zinc-free ISO VG 46 circulation and bearing oil. Outstanding oxidation resistance and corrosion protection for circulation systems, rolling element bearings and lightly loaded gearboxes.","f0":"Zinc-free formula","f1":"Oxidation resistance","f2":"Corrosion protection","f3":"Low foam"},
  "morlina-s2-b-68": {"type":"Circulation / Bearing Oil","description":"Zinc-free ISO VG 68 circulation oil. Flash point of 240°C for safe operation at high temperatures in rolling element bearings and circulation systems.","f0":"Flash point 240°C","f1":"Zinc-free formula","f2":"Oxidation resistance","f3":"Corrosion protection"},
  "morlina-s2-b-100": {"type":"Circulation / Bearing Oil","description":"Zinc-free ISO VG 100 circulation oil. Flash point of 250°C for circulation systems and bearing applications requiring medium-high viscosity.","f0":"Flash point 250°C","f1":"Zinc-free formula","f2":"Extended service interval","f3":"Corrosion protection"},
  "morlina-s2-b-150": {"type":"Circulation / Bearing Oil","description":"Zinc-free ISO VG 150 circulation oil. High oxidation stability for heavy-duty bearings and large industrial circulation systems.","f0":"ISO VG 150 circulation","f1":"Zinc-free formula","f2":"High temperature stability","f3":"Corrosion protection"},
  "morlina-s2-b-220": {"type":"Circulation / Bearing Oil","description":"Zinc-free ISO VG 220 circulation oil. Flash point of 280°C for reliable protection in heavy industrial applications and at high temperatures.","f0":"Flash point 280°C","f1":"Zinc-free formula","f2":"Heavy industrial compatible","f3":"Corrosion protection"},
  "morlina-s2-b-320": {"type":"Circulation / Bearing Oil","description":"Zinc-free ISO VG 320 circulation oil. Flash point of 282°C — the highest viscosity Morlina S2 B for very heavy-duty bearing and circulation applications.","f0":"Highest viscosity grade","f1":"Flash point 282°C","f2":"Zinc-free formula","f3":"Heavy load capacity"},
  "corena-s2-p-68": {"type":"Reciprocating Compressor Oil","description":"High-performance compressor oil specifically developed for reciprocating air compressors. Reliable protection up to 220°C discharge temperature and extended service intervals.","f0":"Reciprocating compressor specialist","f1":"High temperature protection","f2":"Extended service interval","f3":"Carbon deposit prevention"},
  "corena-s2-p-100": {"type":"Reciprocating Compressor Oil","description":"ISO VG 100 compressor oil for reciprocating air compressors. Outstanding protection even at 220°C discharge temperature; excellent oxidation resistance.","f0":"Reciprocating compressor specialist","f1":"High oxidation resistance","f2":"Extended service interval","f3":"Easy water separation"},
  "corena-s2-p-150": {"type":"Reciprocating Compressor Oil","description":"High-viscosity compressor oil for reciprocating air compressors. Carbon deposit prevention, reliable air line protection and extended service intervals.","f0":"High viscosity","f1":"Carbon deposit prevention","f2":"Reliable air lines","f3":"Extended service interval"},
  "corena-s3-r-46": {"type":"Rotary Screw/Vane Compressor Oil","description":"High-quality compressor oil for oil-injected rotary screw and vane compressors. Oil drain life of up to 8,000 hours and low carbon build-up.","f0":"8,000-hour oil life","f1":"Low carbon build-up","f2":"Outstanding oxidation resistance","f3":"Low volatility"},
  "corena-s3-r-68": {"type":"Rotary Screw/Vane Compressor Oil","description":"ISO VG 68 compressor oil for oil-injected rotary screw and vane compressors. 8,000-hour oil life, low volatility and excellent cooling performance.","f0":"8,000-hour oil life","f1":"Low volatility","f2":"Excellent cooling","f3":"Rust and corrosion protection"},
  "corena-s4-r-46": {"type":"Synthetic Rotary Screw/Vane Compressor Oil","description":"Fully synthetic compressor oil for rotary screw and vane compressors. Oil drain life up to 8,000 hours, high temperature stability and minimum carbon deposit.","f0":"Fully synthetic","f1":"8,000-hour oil life","f2":"High temperature stability","f3":"Minimum carbon deposit"},
  "corena-s4-r-68": {"type":"Synthetic Rotary Screw/Vane Compressor Oil","description":"Fully synthetic ISO VG 68 rotary compressor oil. 8,000-hour oil life and superior thermal stability for systems operating at high temperatures.","f0":"Fully synthetic","f1":"High temperature compressors","f2":"8,000-hour oil life","f3":"Superior oxidation resistance"},
  "refrigeration-s4-fr-f-32": {"type":"Refrigeration Compressor Oil (Alkylbenzene)","description":"Alkylbenzene-based synthetic refrigeration compressor oil. Designed for ammonia (R717) and HCFC systems; pour point of -39°C and excellent low-temperature performance.","f0":"Ammonia system specialist","f1":"Alkylbenzene synthetic","f2":"Excellent low temperature","f3":"Pour point -39°C"},
  "refrigeration-s4-fr-f-68": {"type":"Refrigeration Compressor Oil (Alkylbenzene)","description":"Alkylbenzene-based ISO VG 68 synthetic refrigeration compressor oil. High oxidation stability and extended oil drain intervals for ammonia and HCFC systems.","f0":"Alkylbenzene synthetic","f1":"High oxidation stability","f2":"Ammonia system compatible","f3":"Extended oil life"},
  "refrigeration-s4-fr-f-100": {"type":"Refrigeration Compressor Oil (Alkylbenzene)","description":"Alkylbenzene-based ISO VG 100 synthetic refrigeration compressor oil. Outstanding performance in ammonia systems at evaporation temperatures below -33°C.","f0":"High viscosity refrigeration oil","f1":"Alkylbenzene synthetic","f2":"Ammonia system specialist","f3":"Miscible with mineral oil"},
  "refrigeration-s4-fr-v-32": {"type":"Refrigeration Compressor Oil (Alkylbenzene)","description":"Alkylbenzene-based synthetic refrigeration oil. For CFC/HCFC and ammonia systems; superior miscibility with mineral oils at low temperatures.","f0":"CFC/HCFC compatible","f1":"Superior low temperature miscibility","f2":"Alkylbenzene synthetic","f3":"Miscible with mineral oil"},
  "refrigeration-s4-fr-v-46": {"type":"Refrigeration Compressor Oil (Alkylbenzene)","description":"Alkylbenzene-based ISO VG 46 synthetic refrigeration oil. Outstanding low-temperature miscibility and extended oil drain intervals for CFC/HCFC and ammonia systems.","f0":"CFC/HCFC compatible","f1":"Alkylbenzene synthetic","f2":"Extended oil life","f3":"Ammonia system compatible"},
  "refrigeration-s4-fr-v-68": {"type":"Refrigeration Compressor Oil (Alkylbenzene)","description":"Alkylbenzene-based ISO VG 68 synthetic refrigeration oil. High oxidation stability and excellent seal compatibility for ammonia and HCFC systems.","f0":"High oxidation stability","f1":"CFC/HCFC compatible","f2":"Alkylbenzene synthetic","f3":"Extended oil life"},
  "tonna-s3-m-68": {"type":"Slideway Oil","description":"Specialty slideway oil for machine tool slideways and reciprocating tables. Eliminates stick-slip vibration for precise feed motion and superior surface quality.","f0":"Stick-slip prevention","f1":"Precise feed control","f2":"CNC machine compatible","f3":"Corrosion prevention"},
  "tonna-s3-m-220": {"type":"Slideway Oil","description":"ISO VG 220 slideway oil for heavy-duty slideway applications. High-viscosity formula for stick-slip prevention and superior surface quality in slow feed mechanisms.","f0":"Heavy-duty slideways","f1":"Stick-slip prevention","f2":"High viscosity stability","f3":"Water separation"},
  "turbo-t-32": {"type":"Turbine Oil","description":"Industrial turbine oil developed for high-powered steam turbines. Approved by Siemens, ABB and Alstom; excellent oxidation stability and water separation performance.","f0":"Siemens and ABB approved","f1":"Excellent oxidation stability","f2":"Superior water separation","f3":"Excellent filterability"},
  "turbo-t-46": {"type":"Turbine Oil","description":"ISO VG 46 industrial turbine oil for steam turbines. Extended system life through corrosion protection, excellent water separation and outstanding filtration.","f0":"Siemens and ABB approved","f1":"Corrosion protection","f2":"Excellent water separation","f3":"Turbo compressor compatible"},
  "turbo-t-68": {"type":"Turbine Oil","description":"ISO VG 68 turbine oil for high-powered steam turbines. For industrial applications and turbo compressors requiring high rust and oxidation protection.","f0":"High oxidation protection","f1":"Siemens and ABB approved","f2":"Excellent filterability","f3":"Air release property"},
  "turbo-cc-32": {"type":"Combined Cycle Turbine Oil","description":"Specialty industrial turbine oil for combined cycle systems. Approved by Siemens, ABB, GE and Westinghouse; heavy-duty gear capacity and excellent oxidation stability.","f0":"Combined cycle turbines","f1":"Heavy-duty gear capacity","f2":"Siemens/GE/ABB approved","f3":"Excellent oxidation stability"},
  "turbo-cc-46": {"type":"Combined Cycle Turbine Oil","description":"ISO VG 46 turbine oil for combined cycle systems. Can be used as a single-fill oil for turbines and heavy-duty gear systems in steam and gas turbines.","f0":"Combined cycle specialist","f1":"Single-fill system oil","f2":"Multiple OEM approvals","f3":"Excellent water separation"},
  "turbo-fluid-dr-46": {"type":"Turbine / Circulation Oil","description":"High-performance industrial turbine and circulation oil. Special formulation provides extended service life and reliable protection in turbine systems.","f0":"Turbine and circulation applications","f1":"High thermal stability","f2":"Oxidation resistance","f3":"Extended service life"},
  "turbo-j-32": {"type":"Turbine Oil","description":"ISO VG 32 turbine oil for industrial steam turbines. High oxidation and rust protection for main shaft bearings, mechanical gears and control valves.","f0":"High oxidation protection","f1":"Siemens and ABB approved","f2":"Excellent water separation","f3":"Turbo compressor compatible"},
  "diala-s4-zx-i": {"type":"Transformer Oil","description":"Next-generation transformer oil produced with GTL technology. Zero sulfur content, five times the industry-standard oxidation stability and extended equipment life. For power transformers and high-voltage switchgear.","f0":"GTL technology","f1":"Zero sulfur content","f2":"5x oxidation stability","f3":"ABB and Siemens approved"},
  "heat-transfer-oil-s2": {"type":"Heat Transfer Oil","description":"High-performance heat transfer oil capable of operating up to 320°C in closed heat transfer systems. Low vapor pressure, high heat transfer coefficient and thermal stability.","f0":"320°C operating temperature","f1":"High thermal stability","f2":"Low vapor pressure","f3":"Wide application range"},
  "naturelle-hf-e": {"type":"Biodegradable Hydraulic Oil","description":"Environmentally friendly biodegradable hydraulic oil. Performance across a wide temperature range with a high viscosity index; for riverside, forestry and marine applications.","f0":"Biodegradable","f1":"Environmentally friendly","f2":"High viscosity index","f3":"Denison HF-0 approved"},
  "tequla-v-32": {"type":"High VI Hydraulic Oil","description":"High viscosity index industrial hydraulic oil. Stable viscosity performance in variable temperature conditions with outstanding anti-wear protection.","f0":"High viscosity index","f1":"Thermal stability","f2":"Outstanding anti-wear protection","f3":"Excellent filterability"},
  "textile-needle-s2-m-32": {"type":"Textile Machine Oil","description":"Needle mechanism oil developed for the textile industry. Washable formulation with fast pre-dyeing wash-off and starch build-up prevention.","f0":"Washable formulation","f1":"Starch build-up prevention","f2":"Dye-house compatible","f3":"Corrosion protection"},
  "air-tool-s2-a-100": {"type":"Pneumatic Tool Oil","description":"Impact drill and pneumatic tool oil. Special mineral base oil and additives providing outstanding anti-wear protection under impact load conditions and excellent cold-weather fluidity.","f0":"Impact load protection","f1":"Outstanding anti-wear protection","f2":"Cold weather fluidity","f3":"High oxidation resistance"},
  "edelex-956": {"type":"Naphthenic Process Oil","description":"Naphthenic process oil with high solvency. Used as an extender in rubber, plastic and thermoplastic elastomer production; as a carrier fluid in textile and leather processing.","f0":"High naphthenic solvency","f1":"Rubber/plastic extender","f2":"FDA compliant","f3":"Low aromatic content"},
  "catenex-s-321": {"type":"Paraffinic Process Oil","description":"High flash point paraffinic process oil. Used as an extender in automotive tire, synthetic rubber and adhesive production; reference oil in rubber formulations.","f0":"High flash point","f1":"Paraffinic process oil","f2":"Reference for rubber formulations","f3":"FDA compliant"},
  "ondina-x-415": {"type":"White Mineral Oil (Pharmaceutical)","description":"Pharmaceutical-grade white mineral oil. Colorless, odorless and flavorless formulation with polycyclic aromatics removed; FDA §172.878 approved for cosmetic, pharmaceutical and food sectors.","f0":"Pharmaceutical grade","f1":"Colorless and odorless","f2":"FDA §172.878 approved","f3":"Polycyclic aromatics removed"},
  "ondina-x-432": {"type":"White Mineral Oil (Pharmaceutical)","description":"Pharmaceutical-grade white mineral oil. Colorless, odorless formulation for cosmetics, pharmaceuticals and food packaging; FDA and European Pharmacopoeia compliant.","f0":"Pharmaceutical grade","f1":"FDA §172.878 approved","f2":"Colorless/odorless","f3":"European Pharmacopoeia compliant"},
  "ondina-x-420": {"type":"White Mineral Oil (Pharmaceutical)","description":"Pharmaceutical-grade white mineral oil. Colorless, odorless formulation for cosmetics, pharmaceuticals and food sectors; FDA and European Pharmacopoeia compliant.","f0":"Pharmaceutical grade","f1":"FDA compliant","f2":"Colorless/odorless","f3":"European Pharmacopoeia compliant"},
  "ensis-engine-oil-30": {"type":"Engine Protection / Conservation Oil","description":"Conservation oil for engine protection during long-term storage and transportation. Forms a strong barrier against rust and corrosion.","f0":"Engine conservation","f1":"Rust and corrosion protection","f2":"Long-term storage compatible","f3":"SAE 30"},
  "ensis-dw-2462": {"type":"Conservation / Anti-Rust Oil","description":"Specialty anti-rust conservation oil for long-term protection of industrial equipment and metal surfaces.","f0":"Anti-rust protection","f1":"Metal surface protection","f2":"Long-term protection","f3":"Industrial conservation"},
  "irus-fluid-c": {"type":"Special Industrial Fluid","description":"High-performance industrial fluid developed for specialized industrial applications.","f0":"Specialized industrial formulation","f1":"High performance","f2":"Industrial systems","f3":"Reliable protection"},
}

# ── Russian ──────────────────────────────────────────────────────────────────

RU = {
  "tellus-s2-m-32": {"type":"Гидравлическое масло","description":"Высокоэффективное гидравлическое масло по ISO 11158 HM. Исключительная термическая стабильность, отличная стойкость к окислению и защита от износа для промышленных гидравлических систем.","f0":"Термическая стабильность","f1":"Стойкость к окислению","f2":"Защита от износа","f3":"Отличная фильтруемость"},
  "tellus-s2-m-46": {"type":"Гидравлическое масло","description":"Высокоэффективное гидравлическое масло ISO 11158 HM наиболее распространённого класса вязкости. Превосходная термическая стабильность, защита от окисления и износа.","f0":"Термическая стабильность","f1":"Выдающаяся защита от износа","f2":"Отличная фильтруемость","f3":"Водоотделение"},
  "tellus-s2-m-68": {"type":"Гидравлическое масло","description":"Высокоэффективное гидравлическое масло ISO 11158 HM для высокотемпературных и тяжёлых режимов работы. Превосходная термическая стабильность и защита от износа.","f0":"Стабильность при высоких температурах","f1":"Выдающаяся защита от износа","f2":"Отличная фильтруемость","f3":"Водоотделение"},
  "tellus-s2-m-100": {"type":"Гидравлическое масло","description":"Высоковязкое гидравлическое масло ISO 11158 HM. Превосходная защита для вакуумных насосов и высоконапорных гидравлических систем.","f0":"Стабильность вязкости","f1":"Стойкость к окислению","f2":"Защита от износа","f3":"Водоотделение"},
  "tellus-s2-v-15": {"type":"Гидравлическое масло с высоким ВИ","description":"Гидравлическое масло с высоким ВИ и стабильной вязкостью в широком диапазоне температур. Идеально для холодных условий и систем точного управления.","f0":"Высокий индекс вязкости","f1":"Широкий диапазон температур","f2":"Термическая стабильность","f3":"Отличная фильтруемость"},
  "tellus-s2-v-22": {"type":"Гидравлическое масло с высоким ВИ","description":"Гидравлическое масло с высоким ВИ для постоянной вязкости в широком диапазоне температур. Подходит для промышленных и мобильных систем в переменных температурных условиях.","f0":"Высокий индекс вязкости","f1":"Широкий температурный диапазон","f2":"Защита от износа","f3":"Стойкость к окислению"},
  "tellus-s2-v-32": {"type":"Гидравлическое масло с высоким ВИ","description":"Гидравлическое масло с высоким ВИ для стабильной работы в широком диапазоне температур. Подходит для наружных машин и мобильных систем.","f0":"Высокий ВИ","f1":"Широкий диапазон температур","f2":"Допуск Denison HF-0","f3":"Водоотделение"},
  "tellus-s2-v-46": {"type":"Гидравлическое масло с высоким ВИ","description":"Формула с высоким ВИ для наиболее распространённого класса гидравлической вязкости. Превосходная защита насосов и стабильная работа в промышленных и мобильных системах.","f0":"Высокий индекс вязкости","f1":"Наиболее распространённая вязкость","f2":"Превосходная защита насоса","f3":"Отличная фильтруемость"},
  "tellus-s2-v-68": {"type":"Гидравлическое масло с высоким ВИ","description":"Гидравлическое масло с высоким ВИ для тяжёлых систем с высокими рабочими температурами. Надёжная работа в строительном и горнодобывающем оборудовании.","f0":"Стабильность при высокой температуре","f1":"Для тяжёлых режимов","f2":"Высокий индекс вязкости","f3":"Защита от износа"},
  "tellus-s2-v-100": {"type":"Гидравлическое масло с высоким ВИ","description":"Гидравлическое масло с высоким ВИ для крупных систем с повышенными нагрузками. Стабильная вязкость в медленноходных крупных системах.","f0":"Повышенная нагрузочная способность","f1":"Высокий ВИ","f2":"Для крупных систем","f3":"Термическая стабильность"},
  "tellus-s3-m-32": {"type":"Беззольное гидравлическое масло","description":"Беззольное гидравлическое масло без цинка. Идеально для чувствительных сервоклапанов и систем с компонентами из серебра или магниевых сплавов.","f0":"Формула без цинка","f1":"Совместимость с сервоклапанами","f2":"Для тонких фильтров","f3":"Широкая системная совместимость"},
  "tellus-s3-m-46": {"type":"Беззольное гидравлическое масло","description":"Беззольное гидравлическое масло без цинка для защиты чувствительных сервоклапанов и компонентов из сплавов. Наиболее распространённый промышленный класс вязкости.","f0":"Беззольная формула","f1":"Совместимость с сервоклапанами","f2":"Превосходная окислительная стабильность","f3":"Для тонких фильтров"},
  "tellus-s3-m-68": {"type":"Беззольное гидравлическое масло","description":"Беззольное гидравлическое масло без цинка для высоких температур и тяжёлых нагрузок. Подходит для промышленных прессов и строительного оборудования.","f0":"Формула без цинка","f1":"Стабильность при высоких температурах","f2":"Высокая нагрузочная способность","f3":"Противоизносная защита"},
  "tellus-s3-m-100": {"type":"Беззольное гидравлическое масло","description":"Беззольная формула без цинка для превосходной защиты высоковязких крупных гидравлических систем. Для тяжёлых прессов и промышленных предприятий.","f0":"Формула без цинка","f1":"Повышенная нагрузочная способность","f2":"Для крупных систем","f3":"Расширенные интервалы замены"},
  "tellus-s4-me-32": {"type":"Энергосберегающее гидравлическое масло","description":"Энергосберегающее гидравлическое масло на синтетической основе. Современная рецептура повышает эффективность системы при длительном сроке службы масла.","f0":"Экономия энергии","f1":"Синтетическая технология","f2":"Долгий срок службы масла","f3":"Превосходная стойкость к окислению"},
  "tellus-s4-me-46": {"type":"Энергосберегающее гидравлическое масло","description":"Энергосберегающее гидравлическое масло на синтетической основе наиболее распространённого класса вязкости. Повышает эффективность системы и увеличивает интервалы замены.","f0":"Экономия энергии","f1":"Синтетическая технология","f2":"Расширенный интервал замены","f3":"Превосходная противоизносная защита"},
  "tellus-s4-vx-32": {"type":"Гидравлическое масло с широким диапазоном температур","description":"Гидравлическое масло на синтетической основе с постоянной вязкостью в очень широком диапазоне температур. Превосходная работа от арктических условий до высоких температур.","f0":"Очень широкий диапазон температур","f1":"Синтетическая технология","f2":"Высокий индекс ВИ","f3":"Преимущество холодного пуска"},
  "morlina-s2-bl-5": {"type":"Циркуляционное / Турбинное масло","description":"Циркуляционное масло без цинка сверхнизкой вязкости. Идеально для высокоскоростных подшипников и прецизионных систем циркуляции; температура застывания -60°C.","f0":"Формула без цинка","f1":"Сверхнизкая вязкость","f2":"Температура застывания -60°C","f3":"Стойкость к окислению"},
  "morlina-s2-bl-10": {"type":"Циркуляционное / Турбинное масло","description":"Циркуляционное масло без цинка низкой вязкости. Превосходная окислительная стабильность для паровых турбин, газовых турбин и высокоскоростных систем циркуляции.","f0":"Турбинное водоотделение","f1":"Длительная защита от окисления","f2":"Допуски Siemens и GE","f3":"Противопенная защита"},
  "morlina-s2-bl-22": {"type":"Циркуляционное / Турбинное масло","description":"Циркуляционное масло без цинка ISO VG 22. Высокая стойкость к окислению и защита от коррозии для подшипников скольжения и качения и прецизионных систем.","f0":"Формула без цинка","f1":"Высокая стойкость к окислению","f2":"Защита от коррозии","f3":"Низкое пенообразование"},
  "morlina-s2-b-46": {"type":"Циркуляционное / Подшипниковое масло","description":"Циркуляционное масло и масло для подшипников без цинка ISO VG 46. Превосходная стойкость к окислению и защита от коррозии для систем циркуляции и лёгких редукторов.","f0":"Формула без цинка","f1":"Стойкость к окислению","f2":"Защита от коррозии","f3":"Низкое пенообразование"},
  "morlina-s2-b-68": {"type":"Циркуляционное / Подшипниковое масло","description":"Циркуляционное масло без цинка ISO VG 68. Температура вспышки 240°C для безопасной работы при высоких температурах в подшипниках качения и системах циркуляции.","f0":"Температура вспышки 240°C","f1":"Формула без цинка","f2":"Стойкость к окислению","f3":"Защита от коррозии"},
  "morlina-s2-b-100": {"type":"Циркуляционное / Подшипниковое масло","description":"Циркуляционное масло без цинка ISO VG 100. Температура вспышки 250°C для систем циркуляции и подшипниковых приложений средне-высокой вязкости.","f0":"Температура вспышки 250°C","f1":"Формула без цинка","f2":"Расширенный интервал замены","f3":"Защита от коррозии"},
  "morlina-s2-b-150": {"type":"Циркуляционное / Подшипниковое масло","description":"Циркуляционное масло без цинка ISO VG 150. Высокая окислительная стабильность для тяжёлых подшипников и крупных промышленных систем циркуляции.","f0":"ISO VG 150 циркуляция","f1":"Формула без цинка","f2":"Стабильность при высоких температурах","f3":"Защита от коррозии"},
  "morlina-s2-b-220": {"type":"Циркуляционное / Подшипниковое масло","description":"Циркуляционное масло без цинка ISO VG 220. Температура вспышки 280°C для надёжной защиты в тяжёлых промышленных условиях.","f0":"Температура вспышки 280°C","f1":"Формула без цинка","f2":"Для тяжёлой промышленности","f3":"Защита от коррозии"},
  "morlina-s2-b-320": {"type":"Циркуляционное / Подшипниковое масло","description":"Циркуляционное масло без цинка ISO VG 320. Температура вспышки 282°C — масло Morlina S2 B наивысшего класса вязкости для очень тяжёлых подшипниковых и циркуляционных применений.","f0":"Наивысший класс вязкости","f1":"Температура вспышки 282°C","f2":"Формула без цинка","f3":"Высокая нагрузочная способность"},
  "corena-s2-p-68": {"type":"Масло для поршневых компрессоров","description":"Высокоэффективное компрессорное масло, разработанное специально для поршневых воздушных компрессоров. Надёжная защита при температуре нагнетания до 220°C и расширенные интервалы обслуживания.","f0":"Для поршневых компрессоров","f1":"Защита при высоких температурах","f2":"Расширенный интервал обслуживания","f3":"Предотвращение отложений углерода"},
  "corena-s2-p-100": {"type":"Масло для поршневых компрессоров","description":"Компрессорное масло ISO VG 100 для поршневых воздушных компрессоров. Превосходная защита даже при температуре нагнетания 220°C; отличная стойкость к окислению.","f0":"Для поршневых компрессоров","f1":"Высокая стойкость к окислению","f2":"Расширенный интервал обслуживания","f3":"Лёгкое водоотделение"},
  "corena-s2-p-150": {"type":"Масло для поршневых компрессоров","description":"Высоковязкое компрессорное масло для поршневых воздушных компрессоров. Предотвращение отложений углерода, надёжная защита воздушных линий и расширенные интервалы обслуживания.","f0":"Высокая вязкость","f1":"Предотвращение отложений углерода","f2":"Надёжные воздушные линии","f3":"Расширенный интервал обслуживания"},
  "corena-s3-r-46": {"type":"Масло для винтовых/пластинчатых компрессоров","description":"Высококачественное компрессорное масло для маслонаполненных винтовых и пластинчатых компрессоров. Ресурс масла до 8000 часов и низкие углеродные отложения.","f0":"Ресурс масла 8000 часов","f1":"Низкие углеродные отложения","f2":"Выдающаяся стойкость к окислению","f3":"Низкая летучесть"},
  "corena-s3-r-68": {"type":"Масло для винтовых/пластинчатых компрессоров","description":"Компрессорное масло ISO VG 68 для маслонаполненных винтовых и пластинчатых компрессоров. Ресурс 8000 часов, низкая летучесть и отличная охлаждающая способность.","f0":"Ресурс масла 8000 часов","f1":"Низкая летучесть","f2":"Отличное охлаждение","f3":"Защита от ржавчины и коррозии"},
  "corena-s4-r-46": {"type":"Синтетическое масло для винтовых/пластинчатых компрессоров","description":"Полностью синтетическое компрессорное масло для роторных винтовых и пластинчатых компрессоров. Ресурс масла до 8000 часов, высокотемпературная стабильность и минимальные углеродные отложения.","f0":"Полностью синтетическое","f1":"Ресурс масла 8000 часов","f2":"Стабильность при высоких температурах","f3":"Минимальные углеродные отложения"},
  "corena-s4-r-68": {"type":"Синтетическое масло для винтовых/пластинчатых компрессоров","description":"Полностью синтетическое роторное компрессорное масло ISO VG 68. Ресурс 8000 часов и превосходная термическая стабильность для систем с высокими рабочими температурами.","f0":"Полностью синтетическое","f1":"Для высокотемпературных компрессоров","f2":"Ресурс масла 8000 часов","f3":"Превосходная стойкость к окислению"},
  "refrigeration-s4-fr-f-32": {"type":"Холодильное компрессорное масло (алкилбензол)","description":"Синтетическое холодильное компрессорное масло на основе алкилбензола. Для систем на аммиаке (R717) и HCFC; температура застывания -39°C и отличные низкотемпературные свойства.","f0":"Для аммиачных систем","f1":"Алкилбензольная синтетика","f2":"Отличные низкотемпературные свойства","f3":"Температура застывания -39°C"},
  "refrigeration-s4-fr-f-68": {"type":"Холодильное компрессорное масло (алкилбензол)","description":"Синтетическое холодильное компрессорное масло на основе алкилбензола ISO VG 68. Высокая окислительная стабильность и расширенные интервалы замены для аммиачных и HCFC-систем.","f0":"Алкилбензольная синтетика","f1":"Высокая окислительная стабильность","f2":"Совместимость с аммиачными системами","f3":"Длительный ресурс масла"},
  "refrigeration-s4-fr-f-100": {"type":"Холодильное компрессорное масло (алкилбензол)","description":"Синтетическое холодильное компрессорное масло на основе алкилбензола ISO VG 100. Превосходная работа в аммиачных системах при температурах испарения ниже -33°C.","f0":"Высоковязкое холодильное масло","f1":"Алкилбензольная синтетика","f2":"Для аммиачных систем","f3":"Смешивается с минеральным маслом"},
  "refrigeration-s4-fr-v-32": {"type":"Холодильное компрессорное масло (алкилбензол)","description":"Синтетическое холодильное масло на основе алкилбензола. Для систем CFC/HCFC и аммиака; превосходное смешение с минеральными маслами при низких температурах.","f0":"Совместимость с CFC/HCFC","f1":"Превосходное смешение при низких температурах","f2":"Алкилбензольная синтетика","f3":"Смешивается с минеральным маслом"},
  "refrigeration-s4-fr-v-46": {"type":"Холодильное компрессорное масло (алкилбензол)","description":"Синтетическое холодильное масло на основе алкилбензола ISO VG 46. Превосходное низкотемпературное смешение и расширенные интервалы замены для CFC/HCFC и аммиачных систем.","f0":"Совместимость с CFC/HCFC","f1":"Алкилбензольная синтетика","f2":"Длительный ресурс масла","f3":"Совместимость с аммиачными системами"},
  "refrigeration-s4-fr-v-68": {"type":"Холодильное компрессорное масло (алкилбензол)","description":"Синтетическое холодильное масло на основе алкилбензола ISO VG 68. Высокая окислительная стабильность и отличная совместимость с уплотнениями для аммиачных и HCFC-систем.","f0":"Высокая окислительная стабильность","f1":"Совместимость с CFC/HCFC","f2":"Алкилбензольная синтетика","f3":"Длительный ресурс масла"},
  "tonna-s3-m-68": {"type":"Масло для направляющих","description":"Специальное масло для направляющих станков и возвратно-поступательных столов. Устраняет скачкообразное движение для точного перемещения и высокого качества поверхности.","f0":"Предотвращение скачкообразного движения","f1":"Точное управление подачей","f2":"Совместимость с ЧПУ-станками","f3":"Защита от коррозии"},
  "tonna-s3-m-220": {"type":"Масло для направляющих","description":"Масло для направляющих ISO VG 220 для тяжёлых применений. Высоковязкая формула для предотвращения скачкообразного движения и превосходного качества поверхности.","f0":"Тяжёлые применения","f1":"Предотвращение скачкообразного движения","f2":"Высокая стабильность вязкости","f3":"Водоотделение"},
  "turbo-t-32": {"type":"Турбинное масло","description":"Промышленное турбинное масло для мощных паровых турбин. Допущено Siemens, ABB и Alstom; отличная окислительная стабильность и водоотделение.","f0":"Допуски Siemens и ABB","f1":"Отличная окислительная стабильность","f2":"Превосходное водоотделение","f3":"Отличная фильтруемость"},
  "turbo-t-46": {"type":"Турбинное масло","description":"Промышленное турбинное масло ISO VG 46 для паровых турбин. Длительный срок службы системы благодаря защите от коррозии, отличному водоотделению и фильтрации.","f0":"Допуски Siemens и ABB","f1":"Защита от коррозии","f2":"Отличное водоотделение","f3":"Совместимость с турбокомпрессорами"},
  "turbo-t-68": {"type":"Турбинное масло","description":"Турбинное масло ISO VG 68 для мощных паровых турбин. Для промышленных применений и турбокомпрессоров с высокими требованиями к защите от ржавчины и окисления.","f0":"Высокая защита от окисления","f1":"Допуски Siemens и ABB","f2":"Отличная фильтруемость","f3":"Деаэрирующая способность"},
  "turbo-cc-32": {"type":"Турбинное масло для установок комбинированного цикла","description":"Специальное промышленное турбинное масло для установок комбинированного цикла. Допущено Siemens, ABB, GE и Westinghouse; высокая нагрузочная способность для шестерён и отличная окислительная стабильность.","f0":"Турбины комбинированного цикла","f1":"Нагрузочная способность редукторов","f2":"Допуски Siemens/GE/ABB","f3":"Отличная окислительная стабильность"},
  "turbo-cc-46": {"type":"Турбинное масло для установок комбинированного цикла","description":"Турбинное масло ISO VG 46 для установок комбинированного цикла. Может применяться как единое масло для турбин и тяжелонагруженных редукторов.","f0":"Специалист по комбинированному циклу","f1":"Единое масло для системы","f2":"Многочисленные допуски OEM","f3":"Отличное водоотделение"},
  "turbo-fluid-dr-46": {"type":"Турбинное / Циркуляционное масло","description":"Высокоэффективное промышленное турбинное и циркуляционное масло. Специальная рецептура обеспечивает длительный срок службы и надёжную защиту в турбинных системах.","f0":"Турбинные и циркуляционные применения","f1":"Высокая термическая стабильность","f2":"Стойкость к окислению","f3":"Длительный срок службы"},
  "turbo-j-32": {"type":"Турбинное масло","description":"Турбинное масло ISO VG 32 для промышленных паровых турбин. Высокая защита от окисления и ржавчины для главных подшипников, механических редукторов и регулирующих клапанов.","f0":"Высокая защита от окисления","f1":"Допуски Siemens и ABB","f2":"Отличное водоотделение","f3":"Совместимость с турбокомпрессорами"},
  "diala-s4-zx-i": {"type":"Трансформаторное масло","description":"Трансформаторное масло нового поколения, произведённое по технологии GTL. Нулевое содержание серы, пятикратная окислительная стабильность по сравнению с отраслевым стандартом и длительный срок службы оборудования.","f0":"Технология GTL","f1":"Нулевое содержание серы","f2":"5x окислительная стабильность","f3":"Допуски ABB и Siemens"},
  "heat-transfer-oil-s2": {"type":"Теплоноситель","description":"Высокоэффективный теплоноситель для закрытых систем теплопередачи с рабочей температурой до 320°C. Низкое давление паров, высокий коэффициент теплоотдачи и термическая стабильность.","f0":"Рабочая температура 320°C","f1":"Высокая термическая стабильность","f2":"Низкое давление паров","f3":"Широкий спектр применений"},
  "naturelle-hf-e": {"type":"Биоразлагаемое гидравлическое масло","description":"Экологичное биоразлагаемое гидравлическое масло. Работа в широком диапазоне температур с высоким ВИ; для применений вблизи водоёмов, в лесном хозяйстве и морских условиях.","f0":"Биоразлагаемое","f1":"Экологически безопасное","f2":"Высокий индекс вязкости","f3":"Допуск Denison HF-0"},
  "tequla-v-32": {"type":"Гидравлическое масло с высоким ВИ","description":"Промышленное гидравлическое масло с высоким ВИ. Стабильная вязкость при переменных температурах и превосходная противоизносная защита.","f0":"Высокий индекс вязкости","f1":"Термическая стабильность","f2":"Выдающаяся противоизносная защита","f3":"Отличная фильтруемость"},
  "textile-needle-s2-m-32": {"type":"Масло для текстильных машин","description":"Масло для игольного механизма, разработанное для текстильной промышленности. Смываемая рецептура с быстрым удалением перед крашением и предотвращением накопления крахмала.","f0":"Смываемая рецептура","f1":"Предотвращение накопления крахмала","f2":"Совместимость с красильным цехом","f3":"Защита от коррозии"},
  "air-tool-s2-a-100": {"type":"Масло для пневматического инструмента","description":"Масло для перфораторов и пневматического инструмента. Специальное минеральное базовое масло с присадками для превосходной противоизносной защиты при ударных нагрузках и отличной текучести в холодных условиях.","f0":"Защита при ударных нагрузках","f1":"Превосходная противоизносная защита","f2":"Текучесть в холодных условиях","f3":"Высокая стойкость к окислению"},
  "edelex-956": {"type":"Нафтеновое технологическое масло","description":"Нафтеновое технологическое масло с высокой растворяющей способностью. Применяется как масло-наполнитель при производстве резины, пластиков и ТПЭ; как несущая жидкость в текстиле и кожевенной обработке.","f0":"Высокая нафтеновая растворяющая способность","f1":"Масло-наполнитель для резины/пластиков","f2":"Соответствие FDA","f3":"Низкое содержание ароматики"},
  "catenex-s-321": {"type":"Парафиновое технологическое масло","description":"Парафиновое технологическое масло с высокой температурой вспышки. Масло-наполнитель при производстве автомобильных шин, синтетического каучука и адгезивов; референсное масло в каучуковых рецептурах.","f0":"Высокая температура вспышки","f1":"Парафиновое технологическое масло","f2":"Референс для каучуковых рецептур","f3":"Соответствие FDA"},
  "ondina-x-415": {"type":"Белое минеральное масло (фармацевтическое)","description":"Белое минеральное масло фармацевтического качества. Бесцветная, без запаха и вкуса рецептура с удалёнными полициклическими ароматиками; допуск FDA §172.878.","f0":"Фармацевтическое качество","f1":"Бесцветное и без запаха","f2":"Допуск FDA §172.878","f3":"Полициклические ароматики удалены"},
  "ondina-x-432": {"type":"Белое минеральное масло (фармацевтическое)","description":"Белое минеральное масло фармацевтического качества. Бесцветная, без запаха рецептура для косметики, фармацевтики и пищевых упаковок; соответствие FDA и Европейской фармакопее.","f0":"Фармацевтическое качество","f1":"Допуск FDA §172.878","f2":"Бесцветное / без запаха","f3":"Соответствие Европейской фармакопее"},
  "ondina-x-420": {"type":"Белое минеральное масло (фармацевтическое)","description":"Белое минеральное масло фармацевтического качества. Бесцветная, без запаха рецептура для косметики, фармацевтики и пищевой отрасли; соответствие FDA и Европейской фармакопее.","f0":"Фармацевтическое качество","f1":"Соответствие FDA","f2":"Бесцветное / без запаха","f3":"Соответствие Европейской фармакопее"},
  "ensis-engine-oil-30": {"type":"Консервационное масло для двигателей","description":"Консервационное масло для защиты двигателей при длительном хранении и транспортировке. Образует надёжный барьер против ржавчины и коррозии.","f0":"Консервация двигателей","f1":"Защита от ржавчины и коррозии","f2":"Совместимость с длительным хранением","f3":"SAE 30"},
  "ensis-dw-2462": {"type":"Консервационное / Антикоррозионное масло","description":"Специальное антикоррозионное консервационное масло для долгосрочной защиты промышленного оборудования и металлических поверхностей.","f0":"Антикоррозионная защита","f1":"Защита металлических поверхностей","f2":"Долгосрочная защита","f3":"Промышленная консервация"},
  "irus-fluid-c": {"type":"Специальная промышленная жидкость","description":"Высокоэффективная промышленная жидкость, разработанная для специализированных промышленных применений.","f0":"Специализированная промышленная рецептура","f1":"Высокая эффективность","f2":"Промышленные системы","f3":"Надёжная защита"},
}

# ── Farsi ────────────────────────────────────────────────────────────────────

FA = {
  "tellus-s2-m-32": {"type":"روغن هیدرولیک","description":"روغن هیدرولیک پرکارایی مطابق ISO 11158 HM. ثبات حرارتی استثنایی، مقاومت عالی در برابر اکسیداسیون و حفاظت در برابر سایش برای سیستم‌های هیدرولیک صنعتی.","f0":"ثبات حرارتی","f1":"مقاومت در برابر اکسیداسیون","f2":"حفاظت در برابر سایش","f3":"قابلیت فیلتراسیون عالی"},
  "tellus-s2-m-46": {"type":"روغن هیدرولیک","description":"روغن هیدرولیک پرکارایی ISO 11158 HM در رایج‌ترین کلاس ویسکوزیته. ثبات حرارتی برتر، مقاومت در برابر اکسیداسیون و حفاظت در برابر سایش.","f0":"ثبات حرارتی","f1":"حفاظت برجسته در برابر سایش","f2":"قابلیت فیلتراسیون عالی","f3":"جداسازی آب"},
  "tellus-s2-m-68": {"type":"روغن هیدرولیک","description":"روغن هیدرولیک پرکارایی ISO 11158 HM برای کاربردهای دما بالا و بارسنگین. ثبات حرارتی برتر و حفاظت برجسته در برابر سایش.","f0":"ثبات در دمای بالا","f1":"حفاظت برجسته در برابر سایش","f2":"قابلیت فیلتراسیون عالی","f3":"جداسازی آب"},
  "tellus-s2-m-100": {"type":"روغن هیدرولیک","description":"روغن هیدرولیک ویسکوزیته بالا مطابق ISO 11158 HM. حفاظت برتر برای پمپ‌های خلأ و سیستم‌های هیدرولیک فشار بالا.","f0":"ثبات ویسکوزیته بالا","f1":"مقاومت در برابر اکسیداسیون","f2":"حفاظت در برابر سایش","f3":"جداسازی آب"},
  "tellus-s2-v-15": {"type":"روغن هیدرولیک با ویسکوزیته ایندکس بالا","description":"روغن هیدرولیک با ویسکوزیته ایندکس بالا و ثبات ویسکوزیته در دامنه دمایی گسترده. ایده‌آل برای محیط‌های سرد و سیستم‌های کنترل دقیق.","f0":"ویسکوزیته ایندکس بالا","f1":"دامنه دمایی گسترده","f2":"ثبات حرارتی","f3":"قابلیت فیلتراسیون عالی"},
  "tellus-s2-v-22": {"type":"روغن هیدرولیک با ویسکوزیته ایندکس بالا","description":"روغن هیدرولیک با ویسکوزیته ایندکس بالا برای ثبات در دامنه دمایی گسترده. مناسب برای سیستم‌های هیدرولیک صنعتی و موبایل در شرایط دمایی متغیر.","f0":"ویسکوزیته ایندکس بالا","f1":"کارایی در دامنه دمایی گسترده","f2":"حفاظت در برابر سایش","f3":"مقاومت در برابر اکسیداسیون"},
  "tellus-s2-v-32": {"type":"روغن هیدرولیک با ویسکوزیته ایندکس بالا","description":"روغن هیدرولیک با ویسکوزیته ایندکس بالا برای کارایی یکنواخت در دامنه دمایی گسترده. مناسب برای ماشین‌آلات فضای باز و سیستم‌های موبایل.","f0":"ویسکوزیته ایندکس بالا","f1":"دامنه دمایی گسترده","f2":"تأییدیه Denison HF-0","f3":"جداسازی آب"},
  "tellus-s2-v-46": {"type":"روغن هیدرولیک با ویسکوزیته ایندکس بالا","description":"فرمولاسیون ویسکوزیته ایندکس بالا برای رایج‌ترین کلاس هیدرولیک. حفاظت برتر از پمپ و کارایی یکنواخت در سیستم‌های صنعتی و موبایل.","f0":"ویسکوزیته ایندکس بالا","f1":"رایج‌ترین ویسکوزیته هیدرولیک","f2":"حفاظت برتر از پمپ","f3":"قابلیت فیلتراسیون عالی"},
  "tellus-s2-v-68": {"type":"روغن هیدرولیک با ویسکوزیته ایندکس بالا","description":"روغن هیدرولیک با ویسکوزیته ایندکس بالا برای سیستم‌های بارسنگین با دمای بالا. کارایی قابل اطمینان در تجهیزات ساخت‌وساز و معدن.","f0":"ثبات در دمای بالا","f1":"مناسب برای بار سنگین","f2":"ویسکوزیته ایندکس بالا","f3":"حفاظت در برابر سایش"},
  "tellus-s2-v-100": {"type":"روغن هیدرولیک با ویسکوزیته ایندکس بالا","description":"روغن هیدرولیک با ویسکوزیته ایندکس بالا برای سیستم‌های بزرگ نیازمند ظرفیت بار اضافی. ثبات ویسکوزیته در سیستم‌های بزرگ کندرو.","f0":"ظرفیت بار اضافی","f1":"ویسکوزیته ایندکس بالا","f2":"مناسب برای سیستم‌های بزرگ","f3":"ثبات حرارتی"},
  "tellus-s3-m-32": {"type":"روغن هیدرولیک بدون خاکستر","description":"روغن هیدرولیک بدون خاکستر و بدون روی. ایده‌آل برای سروالوهای حساس و سیستم‌های دارای اجزای آلیاژ نقره یا منیزیم.","f0":"فرمولاسیون بدون روی","f1":"سازگاری با سروالو","f2":"سازگاری با فیلتر ظریف","f3":"سازگاری گسترده با سیستم"},
  "tellus-s3-m-46": {"type":"روغن هیدرولیک بدون خاکستر","description":"روغن هیدرولیک بدون خاکستر و بدون روی برای حفاظت از سروالوهای حساس و اجزای آلیاژی. رایج‌ترین کلاس ویسکوزیته صنعتی.","f0":"فرمولاسیون بدون خاکستر","f1":"سازگاری با سروالو","f2":"ثبات اکسیداسیون برتر","f3":"سازگاری با فیلتر ظریف"},
  "tellus-s3-m-68": {"type":"روغن هیدرولیک بدون خاکستر","description":"روغن هیدرولیک بدون خاکستر و بدون روی برای شرایط دمای بالا و بار سنگین. مناسب برای پرس‌های صنعتی و تجهیزات ساخت‌وساز.","f0":"فرمولاسیون بدون روی","f1":"ثبات در دمای بالا","f2":"ظرفیت بار سنگین","f3":"ضدسایش"},
  "tellus-s3-m-100": {"type":"روغن هیدرولیک بدون خاکستر","description":"فرمولاسیون بدون خاکستر و بدون روی برای حفاظت برتر از سیستم‌های هیدرولیک بزرگ با ویسکوزیته بالا. برای پرس‌های سنگین و تأسیسات صنعتی.","f0":"فرمولاسیون بدون روی","f1":"ظرفیت بار اضافی","f2":"مناسب برای سیستم‌های بزرگ","f3":"فواصل سرویس طولانی"},
  "tellus-s4-me-32": {"type":"روغن هیدرولیک صرفه‌جو در انرژی","description":"روغن هیدرولیک صرفه‌جو در انرژی بر پایه فناوری سنتتیک. فرمولاسیون پیشرفته کارایی سیستم را افزایش داده و عمر روغن را طولانی می‌کند.","f0":"صرفه‌جویی در انرژی","f1":"فناوری سنتتیک","f2":"عمر طولانی روغن","f3":"مقاومت برتر در برابر اکسیداسیون"},
  "tellus-s4-me-46": {"type":"روغن هیدرولیک صرفه‌جو در انرژی","description":"روغن هیدرولیک صرفه‌جو در انرژی بر پایه فناوری سنتتیک در رایج‌ترین کلاس ویسکوزیته. کارایی سیستم را بهبود داده و فواصل تعویض را افزایش می‌دهد.","f0":"صرفه‌جویی در انرژی","f1":"فناوری سنتتیک","f2":"فاصله تعویض طولانی‌تر","f3":"حفاظت برتر در برابر سایش"},
  "tellus-s4-vx-32": {"type":"روغن هیدرولیک با دامنه دمایی گسترده","description":"روغن هیدرولیک بر پایه فناوری سنتتیک با ویسکوزیته ثابت در دامنه دمایی بسیار گسترده. کارایی برتر از شرایط آرکتیک تا دماهای بالا.","f0":"دامنه دمایی بسیار گسترده","f1":"فناوری سنتتیک","f2":"شاخص ویسکوزیته بالا","f3":"مزیت استارت سرد"},
  "morlina-s2-bl-5": {"type":"روغن گردشی / توربین","description":"روغن گردشی بدون روی با ویسکوزیته بسیار پایین. ایده‌آل برای یاتاقان‌های سرعت بالا و سیستم‌های گردشی دقیق با نقطه ریزش -60°C.","f0":"فرمولاسیون بدون روی","f1":"ویسکوزیته بسیار پایین","f2":"نقطه ریزش -60°C","f3":"مقاومت در برابر اکسیداسیون"},
  "morlina-s2-bl-10": {"type":"روغن گردشی / توربین","description":"روغن گردشی بدون روی با ویسکوزیته پایین. ثبات اکسیداسیون برتر برای توربین‌های بخار، توربین‌های گاز و سیستم‌های گردشی سرعت بالا.","f0":"جداسازی آب در سطح توربین","f1":"عمر طولانی در برابر اکسیداسیون","f2":"تأییدیه Siemens و GE","f3":"ضدکف"},
  "morlina-s2-bl-22": {"type":"روغن گردشی / توربین","description":"روغن گردشی بدون روی ISO VG 22. مقاومت بالا در برابر اکسیداسیون و حفاظت از خوردگی برای یاتاقان‌های ساده و غلتشی و سیستم‌های گردشی دقیق.","f0":"فرمولاسیون بدون روی","f1":"مقاومت بالا در برابر اکسیداسیون","f2":"حفاظت از خوردگی","f3":"تمایل کم به کف کردن"},
  "morlina-s2-b-46": {"type":"روغن گردشی / یاتاقان","description":"روغن گردشی و یاتاقان بدون روی ISO VG 46. مقاومت برتر در برابر اکسیداسیون و حفاظت از خوردگی برای سیستم‌های گردشی، یاتاقان‌های غلتشی و گیربکس‌های سبک.","f0":"فرمولاسیون بدون روی","f1":"مقاومت در برابر اکسیداسیون","f2":"حفاظت از خوردگی","f3":"کف کم"},
  "morlina-s2-b-68": {"type":"روغن گردشی / یاتاقان","description":"روغن گردشی بدون روی ISO VG 68. نقطه اشتعال 240°C برای عملکرد ایمن در دماهای بالا در یاتاقان‌های غلتشی و سیستم‌های گردشی.","f0":"نقطه اشتعال 240°C","f1":"فرمولاسیون بدون روی","f2":"مقاومت در برابر اکسیداسیون","f3":"حفاظت از خوردگی"},
  "morlina-s2-b-100": {"type":"روغن گردشی / یاتاقان","description":"روغن گردشی بدون روی ISO VG 100. نقطه اشتعال 250°C برای سیستم‌های گردشی و کاربردهای یاتاقان با ویسکوزیته متوسط-بالا.","f0":"نقطه اشتعال 250°C","f1":"فرمولاسیون بدون روی","f2":"فاصله سرویس طولانی","f3":"حفاظت از خوردگی"},
  "morlina-s2-b-150": {"type":"روغن گردشی / یاتاقان","description":"روغن گردشی بدون روی ISO VG 150. ثبات اکسیداسیون بالا برای یاتاقان‌های بارسنگین و سیستم‌های گردشی صنعتی بزرگ.","f0":"گردشی ISO VG 150","f1":"فرمولاسیون بدون روی","f2":"ثبات در دمای بالا","f3":"حفاظت از خوردگی"},
  "morlina-s2-b-220": {"type":"روغن گردشی / یاتاقان","description":"روغن گردشی بدون روی ISO VG 220. نقطه اشتعال 280°C برای حفاظت قابل اطمینان در کاربردهای صنعتی سنگین.","f0":"نقطه اشتعال 280°C","f1":"فرمولاسیون بدون روی","f2":"سازگاری با صنعت سنگین","f3":"حفاظت از خوردگی"},
  "morlina-s2-b-320": {"type":"روغن گردشی / یاتاقان","description":"روغن گردشی بدون روی ISO VG 320. نقطه اشتعال 282°C — بالاترین کلاس ویسکوزیته Morlina S2 B برای کاربردهای بسیار بارسنگین یاتاقان و گردشی.","f0":"بالاترین کلاس ویسکوزیته","f1":"نقطه اشتعال 282°C","f2":"فرمولاسیون بدون روی","f3":"ظرفیت بار سنگین"},
  "corena-s2-p-68": {"type":"روغن کمپرسور پیستونی","description":"روغن کمپرسور پرکارایی توسعه‌یافته برای کمپرسورهای پیستونی هوا. حفاظت قابل اطمینان تا دمای تخلیه 220°C و فواصل سرویس طولانی.","f0":"متخصص کمپرسور پیستونی","f1":"حفاظت در دمای بالا","f2":"فاصله سرویس طولانی","f3":"جلوگیری از رسوب کربن"},
  "corena-s2-p-100": {"type":"روغن کمپرسور پیستونی","description":"روغن کمپرسور ISO VG 100 برای کمپرسورهای پیستونی هوا. حفاظت برتر حتی در دمای تخلیه 220°C؛ مقاومت عالی در برابر اکسیداسیون.","f0":"متخصص کمپرسور پیستونی","f1":"مقاومت بالا در برابر اکسیداسیون","f2":"فاصله سرویس طولانی","f3":"جداسازی آسان آب"},
  "corena-s2-p-150": {"type":"روغن کمپرسور پیستونی","description":"روغن کمپرسور با ویسکوزیته بالا برای کمپرسورهای پیستونی هوا. جلوگیری از رسوب کربن، حفاظت قابل اطمینان از خطوط هوا و فواصل سرویس طولانی.","f0":"ویسکوزیته بالا","f1":"جلوگیری از رسوب کربن","f2":"خطوط هوای قابل اطمینان","f3":"فاصله سرویس طولانی"},
  "corena-s3-r-46": {"type":"روغن کمپرسور پیچی/پره‌ای","description":"روغن کمپرسور باکیفیت برای کمپرسورهای پیچی و پره‌ای روغن‌تزریقی. طول عمر روغن تا 8000 ساعت و رسوب کربن پایین.","f0":"طول عمر 8000 ساعته روغن","f1":"رسوب کربن پایین","f2":"مقاومت برجسته در برابر اکسیداسیون","f3":"فرارپذیری پایین"},
  "corena-s3-r-68": {"type":"روغن کمپرسور پیچی/پره‌ای","description":"روغن کمپرسور ISO VG 68 برای کمپرسورهای پیچی و پره‌ای روغن‌تزریقی. طول عمر 8000 ساعت، فرارپذیری پایین و کارایی خنک‌کنندگی عالی.","f0":"طول عمر 8000 ساعته روغن","f1":"فرارپذیری پایین","f2":"خنک‌کنندگی عالی","f3":"حفاظت از زنگ‌زدگی و خوردگی"},
  "corena-s4-r-46": {"type":"روغن کمپرسور پیچی/پره‌ای (سنتتیک)","description":"روغن کمپرسور تمام‌سنتتیک برای کمپرسورهای پیچی و پره‌ای. طول عمر روغن تا 8000 ساعت، ثبات دمایی بالا و حداقل رسوب کربن.","f0":"تمام‌سنتتیک","f1":"طول عمر 8000 ساعته روغن","f2":"ثبات دمایی بالا","f3":"حداقل رسوب کربن"},
  "corena-s4-r-68": {"type":"روغن کمپرسور پیچی/پره‌ای (سنتتیک)","description":"روغن کمپرسور روتاری تمام‌سنتتیک ISO VG 68. طول عمر 8000 ساعت و ثبات حرارتی برتر برای سیستم‌هایی که در دمای بالا کار می‌کنند.","f0":"تمام‌سنتتیک","f1":"کمپرسورهای دمای بالا","f2":"طول عمر 8000 ساعته روغن","f3":"مقاومت برتر در برابر اکسیداسیون"},
  "refrigeration-s4-fr-f-32": {"type":"روغن کمپرسور تبرید (آلکیل بنزن)","description":"روغن کمپرسور تبرید سنتتیک بر پایه آلکیل بنزن. طراحی‌شده برای سیستم‌های آمونیاک (R717) و HCFC؛ نقطه ریزش -39°C و عملکرد عالی در دمای پایین.","f0":"متخصص سیستم‌های آمونیاکی","f1":"سنتتیک آلکیل بنزن","f2":"عملکرد عالی در دمای پایین","f3":"نقطه ریزش -39°C"},
  "refrigeration-s4-fr-f-68": {"type":"روغن کمپرسور تبرید (آلکیل بنزن)","description":"روغن کمپرسور تبرید سنتتیک بر پایه آلکیل بنزن ISO VG 68. ثبات اکسیداسیون بالا و فواصل تعویض طولانی برای سیستم‌های آمونیاک و HCFC.","f0":"سنتتیک آلکیل بنزن","f1":"ثبات اکسیداسیون بالا","f2":"سازگاری با سیستم‌های آمونیاکی","f3":"طول عمر روغن"},
  "refrigeration-s4-fr-f-100": {"type":"روغن کمپرسور تبرید (آلکیل بنزن)","description":"روغن کمپرسور تبرید سنتتیک بر پایه آلکیل بنزن ISO VG 100. عملکرد برجسته در سیستم‌های آمونیاک در دمای تبخیر زیر -33°C.","f0":"روغن تبرید با ویسکوزیته بالا","f1":"سنتتیک آلکیل بنزن","f2":"متخصص سیستم‌های آمونیاکی","f3":"قابل اختلاط با روغن معدنی"},
  "refrigeration-s4-fr-v-32": {"type":"روغن کمپرسور تبرید (آلکیل بنزن)","description":"روغن تبرید سنتتیک بر پایه آلکیل بنزن. برای سیستم‌های CFC/HCFC و آمونیاک؛ اختلاط‌پذیری برتر با روغن‌های معدنی در دمای پایین.","f0":"سازگاری با CFC/HCFC","f1":"اختلاط برتر در دمای پایین","f2":"سنتتیک آلکیل بنزن","f3":"قابل اختلاط با روغن معدنی"},
  "refrigeration-s4-fr-v-46": {"type":"روغن کمپرسور تبرید (آلکیل بنزن)","description":"روغن تبرید سنتتیک بر پایه آلکیل بنزن ISO VG 46. اختلاط‌پذیری برجسته در دمای پایین و فواصل تعویض طولانی برای سیستم‌های CFC/HCFC و آمونیاک.","f0":"سازگاری با CFC/HCFC","f1":"سنتتیک آلکیل بنزن","f2":"طول عمر روغن","f3":"سازگاری با سیستم‌های آمونیاکی"},
  "refrigeration-s4-fr-v-68": {"type":"روغن کمپرسور تبرید (آلکیل بنزن)","description":"روغن تبرید سنتتیک بر پایه آلکیل بنزن ISO VG 68. ثبات اکسیداسیون بالا و سازگاری عالی با آب‌بندها برای سیستم‌های آمونیاک و HCFC.","f0":"ثبات اکسیداسیون بالا","f1":"سازگاری با CFC/HCFC","f2":"سنتتیک آلکیل بنزن","f3":"طول عمر روغن"},
  "tonna-s3-m-68": {"type":"روغن گایدوی","description":"روغن گایدوی مخصوص برای گایدوی‌های ماشین‌ابزار و میزهای رفت‌وبرگشتی. با حذف لرزش‌های جهش‌و‌توقف برای حرکت تغذیه دقیق و کیفیت سطح عالی.","f0":"جلوگیری از جهش‌و‌توقف","f1":"کنترل دقیق تغذیه","f2":"سازگاری با ماشین‌های CNC","f3":"جلوگیری از خوردگی"},
  "tonna-s3-m-220": {"type":"روغن گایدوی","description":"روغن گایدوی ISO VG 220 برای کاربردهای گایدوی سنگین. فرمولاسیون با ویسکوزیته بالا برای جلوگیری از جهش‌و‌توقف و کیفیت سطح برتر در مکانیزم‌های تغذیه کند.","f0":"کاربردهای گایدوی سنگین","f1":"جلوگیری از جهش‌و‌توقف","f2":"ثبات ویسکوزیته بالا","f3":"جداسازی آب"},
  "turbo-t-32": {"type":"روغن توربین","description":"روغن توربین صنعتی توسعه‌یافته برای توربین‌های بخار قوی. تأیید‌شده توسط Siemens، ABB و Alstom؛ ثبات اکسیداسیون عالی و جداسازی آب.","f0":"تأییدیه Siemens و ABB","f1":"ثبات اکسیداسیون عالی","f2":"جداسازی برتر آب","f3":"قابلیت فیلتراسیون عالی"},
  "turbo-t-46": {"type":"روغن توربین","description":"روغن توربین صنعتی ISO VG 46 برای توربین‌های بخار. طول عمر طولانی سیستم از طریق حفاظت در برابر خوردگی، جداسازی عالی آب و فیلتراسیون.","f0":"تأییدیه Siemens و ABB","f1":"حفاظت در برابر خوردگی","f2":"جداسازی عالی آب","f3":"سازگاری با توربوکمپرسور"},
  "turbo-t-68": {"type":"روغن توربین","description":"روغن توربین ISO VG 68 برای توربین‌های بخار قوی. برای کاربردهای صنعتی و توربوکمپرسورهایی که نیاز به حفاظت بالا در برابر زنگ‌زدگی و اکسیداسیون دارند.","f0":"حفاظت بالا در برابر اکسیداسیون","f1":"تأییدیه Siemens و ABB","f2":"قابلیت فیلتراسیون عالی","f3":"خاصیت هواگیری"},
  "turbo-cc-32": {"type":"روغن توربین سیکل ترکیبی","description":"روغن توربین صنعتی مخصوص برای سیستم‌های سیکل ترکیبی. تأیید‌شده توسط Siemens، ABB، GE و Westinghouse؛ ظرفیت بارگذاری سنگین دنده و ثبات اکسیداسیون عالی.","f0":"توربین‌های سیکل ترکیبی","f1":"ظرفیت بارگذاری سنگین دنده","f2":"تأییدیه Siemens/GE/ABB","f3":"ثبات اکسیداسیون عالی"},
  "turbo-cc-46": {"type":"روغن توربین سیکل ترکیبی","description":"روغن توربین ISO VG 46 برای سیستم‌های سیکل ترکیبی. می‌توان از آن به‌عنوان روغن یکپارچه برای توربین‌ها و سیستم‌های دنده بارسنگین استفاده کرد.","f0":"متخصص سیکل ترکیبی","f1":"روغن یکپارچه سیستم","f2":"تأییدیه‌های متعدد OEM","f3":"جداسازی عالی آب"},
  "turbo-fluid-dr-46": {"type":"روغن توربین / گردشی","description":"روغن توربین صنعتی و گردشی پرکارایی. فرمولاسیون ویژه عمر سرویس طولانی و حفاظت قابل اطمینان در سیستم‌های توربینی فراهم می‌کند.","f0":"کاربردهای توربین و گردشی","f1":"ثبات حرارتی بالا","f2":"مقاومت در برابر اکسیداسیون","f3":"طول عمر سرویس"},
  "turbo-j-32": {"type":"روغن توربین","description":"روغن توربین ISO VG 32 برای توربین‌های بخار صنعتی. حفاظت بالا در برابر اکسیداسیون و زنگ‌زدگی برای یاتاقان‌های محور اصلی، دنده‌های مکانیکی و شیرهای کنترل.","f0":"حفاظت بالا در برابر اکسیداسیون","f1":"تأییدیه Siemens و ABB","f2":"جداسازی عالی آب","f3":"سازگاری با توربوکمپرسور"},
  "diala-s4-zx-i": {"type":"روغن ترانسفورماتور","description":"روغن ترانسفورماتور نسل جدید تولیدشده با فناوری GTL. محتوای گوگرد صفر، پنج برابر ثبات اکسیداسیون نسبت به استاندارد صنعت و طول عمر طولانی تجهیزات.","f0":"فناوری GTL","f1":"محتوای گوگرد صفر","f2":"5 برابر ثبات اکسیداسیون","f3":"تأییدیه ABB و Siemens"},
  "heat-transfer-oil-s2": {"type":"روغن انتقال حرارت","description":"روغن انتقال حرارت پرکارایی با قابلیت کار تا 320°C در سیستم‌های انتقال حرارت بسته. فشار بخار پایین، ضریب انتقال حرارت بالا و ثبات حرارتی.","f0":"دمای کار 320°C","f1":"ثبات حرارتی بالا","f2":"فشار بخار پایین","f3":"دامنه کاربردی گسترده"},
  "naturelle-hf-e": {"type":"روغن هیدرولیک زیست‌تخریب‌پذیر","description":"روغن هیدرولیک زیست‌تخریب‌پذیر سازگار با محیط‌زیست. کارایی در دامنه دمایی گسترده با ویسکوزیته ایندکس بالا؛ برای کنار رودخانه، جنگلداری و کاربردهای دریایی.","f0":"زیست‌تخریب‌پذیر","f1":"سازگار با محیط‌زیست","f2":"ویسکوزیته ایندکس بالا","f3":"تأییدیه Denison HF-0"},
  "tequla-v-32": {"type":"روغن هیدرولیک با ویسکوزیته ایندکس بالا","description":"روغن هیدرولیک صنعتی با ویسکوزیته ایندکس بالا. ثبات ویسکوزیته در شرایط دمایی متغیر و حفاظت برجسته در برابر سایش.","f0":"ویسکوزیته ایندکس بالا","f1":"ثبات حرارتی","f2":"حفاظت برجسته در برابر سایش","f3":"قابلیت فیلتراسیون عالی"},
  "textile-needle-s2-m-32": {"type":"روغن ماشین نساجی","description":"روغن مکانیزم سوزن توسعه‌یافته برای صنعت نساجی. فرمولاسیون قابل شستشو با حذف سریع قبل از رنگرزی و جلوگیری از تجمع نشاسته.","f0":"فرمولاسیون قابل شستشو","f1":"جلوگیری از تجمع نشاسته","f2":"سازگاری با رنگخانه","f3":"حفاظت در برابر خوردگی"},
  "air-tool-s2-a-100": {"type":"روغن ابزار پنوماتیک","description":"روغن دریل ضربه‌ای و ابزار پنوماتیک. روغن پایه معدنی ویژه با افزودنی‌ها برای حفاظت برتر در برابر سایش در شرایط بار ضربه‌ای و سیالیت عالی در سرما.","f0":"حفاظت در برابر بار ضربه‌ای","f1":"حفاظت برتر در برابر سایش","f2":"سیالیت در سرما","f3":"مقاومت بالا در برابر اکسیداسیون"},
  "edelex-956": {"type":"روغن فرایندی نفتنیک","description":"روغن فرایندی نفتنیک با قدرت حل‌پذیری بالا. به‌عنوان امتدادده در تولید لاستیک، پلاستیک و الاستومر ترموپلاستیک و به‌عنوان سیال حامل در نساجی و چرم‌کاری استفاده می‌شود.","f0":"قدرت حل‌پذیری نفتنیک بالا","f1":"امتدادده لاستیک/پلاستیک","f2":"مطابقت با FDA","f3":"محتوای آروماتیک پایین"},
  "catenex-s-321": {"type":"روغن فرایندی پارافینیک","description":"روغن فرایندی پارافینیک با نقطه اشتعال بالا. امتدادده در تولید تایر خودرو، لاستیک سنتتیک و چسب؛ روغن مرجع در فرمولاسیون‌های لاستیک.","f0":"نقطه اشتعال بالا","f1":"روغن فرایندی پارافینیک","f2":"مرجع فرمولاسیون‌های لاستیک","f3":"مطابقت با FDA"},
  "ondina-x-415": {"type":"روغن معدنی سفید (دارویی)","description":"روغن معدنی سفید درجه دارویی. فرمولاسیون بی‌رنگ، بی‌بو و بی‌مزه با حذف هیدروکربن‌های آروماتیک چندحلقه‌ای؛ تأیید FDA §172.878.","f0":"درجه دارویی","f1":"بی‌رنگ و بی‌بو","f2":"تأییدیه FDA §172.878","f3":"هیدروکربن‌های آروماتیک چندحلقه‌ای حذف‌شده"},
  "ondina-x-432": {"type":"روغن معدنی سفید (دارویی)","description":"روغن معدنی سفید درجه دارویی. فرمولاسیون بی‌رنگ و بی‌بو برای آرایشی، دارویی و بسته‌بندی غذایی؛ مطابق FDA و فارماکوپه اروپایی.","f0":"درجه دارویی","f1":"تأییدیه FDA §172.878","f2":"بی‌رنگ / بی‌بو","f3":"مطابقت فارماکوپه اروپایی"},
  "ondina-x-420": {"type":"روغن معدنی سفید (دارویی)","description":"روغن معدنی سفید درجه دارویی. فرمولاسیون بی‌رنگ و بی‌بو برای بخش‌های آرایشی، دارویی و غذایی؛ مطابق FDA و فارماکوپه اروپایی.","f0":"درجه دارویی","f1":"مطابقت با FDA","f2":"بی‌رنگ / بی‌بو","f3":"مطابقت فارماکوپه اروپایی"},
  "ensis-engine-oil-30": {"type":"روغن محافظت موتور / کنسرواسیون","description":"روغن کنسرواسیون برای محافظت از موتور در حین انبارداری طولانی‌مدت و حمل‌ونقل. سد مقاوم در برابر زنگ‌زدگی و خوردگی ایجاد می‌کند.","f0":"کنسرواسیون موتور","f1":"محافظت در برابر زنگ‌زدگی و خوردگی","f2":"سازگار با انبارداری طولانی‌مدت","f3":"SAE 30"},
  "ensis-dw-2462": {"type":"روغن کنسرواسیون / ضدزنگ","description":"روغن کنسرواسیون ضدزنگ ویژه برای حفاظت طولانی‌مدت از تجهیزات صنعتی و سطوح فلزی.","f0":"محافظت ضدزنگ","f1":"حفاظت از سطوح فلزی","f2":"حفاظت طولانی‌مدت","f3":"کنسرواسیون صنعتی"},
  "irus-fluid-c": {"type":"سیال صنعتی ویژه","description":"سیال صنعتی پرکارایی توسعه‌یافته برای کاربردهای صنعتی تخصصی.","f0":"فرمولاسیون صنعتی تخصصی","f1":"پرکارایی","f2":"سیستم‌های صنعتی","f3":"حفاظت قابل اطمینان"},
}

# ── Patch helper ─────────────────────────────────────────────────────────────

def patch(lang: str, entries: dict):
    path = os.path.join(MSG, f"{lang}.json")
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    pd = data.setdefault("pd", {})
    pd.update(entries)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"  {lang}.json — added/updated {len(entries)} pd entries")

# ── Main ─────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("Patching tr…")
    patch("tr", load_tr())
    print("Patching en…")
    patch("en", EN)
    print("Patching ru…")
    patch("ru", RU)
    print("Patching fa…")
    patch("fa", FA)
    print("Done.")
