/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MediaRouteImport } from './routes/media'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ExportRouteImport } from './routes/export'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CatalogsRouteImport } from './routes/catalogs'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrIndexRouteImport } from './routes/tr/index'
import { Route as RuIndexRouteImport } from './routes/ru/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as FrIndexRouteImport } from './routes/fr/index'
import { Route as FaIndexRouteImport } from './routes/fa/index'
import { Route as DeIndexRouteImport } from './routes/de/index'
import { Route as ArIndexRouteImport } from './routes/ar/index'
import { Route as TrMediaRouteImport } from './routes/tr/media'
import { Route as TrIndustriesRouteImport } from './routes/tr/industries'
import { Route as TrExportRouteImport } from './routes/tr/export'
import { Route as TrContactRouteImport } from './routes/tr/contact'
import { Route as TrCatalogsRouteImport } from './routes/tr/catalogs'
import { Route as TrBlogRouteImport } from './routes/tr/blog'
import { Route as TrAboutRouteImport } from './routes/tr/about'
import { Route as RuMediaRouteImport } from './routes/ru/media'
import { Route as RuIndustriesRouteImport } from './routes/ru/industries'
import { Route as RuExportRouteImport } from './routes/ru/export'
import { Route as RuContactRouteImport } from './routes/ru/contact'
import { Route as RuCatalogsRouteImport } from './routes/ru/catalogs'
import { Route as RuBlogRouteImport } from './routes/ru/blog'
import { Route as RuAboutRouteImport } from './routes/ru/about'
import { Route as ProductsYokohamaRouteImport } from './routes/products/yokohama'
import { Route as ProductsHiTechRouteImport } from './routes/products/hi-tech'
import { Route as FrMediaRouteImport } from './routes/fr/media'
import { Route as FrIndustriesRouteImport } from './routes/fr/industries'
import { Route as FrExportRouteImport } from './routes/fr/export'
import { Route as FrContactRouteImport } from './routes/fr/contact'
import { Route as FrCatalogsRouteImport } from './routes/fr/catalogs'
import { Route as FrBlogRouteImport } from './routes/fr/blog'
import { Route as FrAboutRouteImport } from './routes/fr/about'
import { Route as FaMediaRouteImport } from './routes/fa/media'
import { Route as FaIndustriesRouteImport } from './routes/fa/industries'
import { Route as FaExportRouteImport } from './routes/fa/export'
import { Route as FaContactRouteImport } from './routes/fa/contact'
import { Route as FaCatalogsRouteImport } from './routes/fa/catalogs'
import { Route as FaBlogRouteImport } from './routes/fa/blog'
import { Route as FaAboutRouteImport } from './routes/fa/about'
import { Route as DeMediaRouteImport } from './routes/de/media'
import { Route as DeIndustriesRouteImport } from './routes/de/industries'
import { Route as DeExportRouteImport } from './routes/de/export'
import { Route as DeContactRouteImport } from './routes/de/contact'
import { Route as DeCatalogsRouteImport } from './routes/de/catalogs'
import { Route as DeBlogRouteImport } from './routes/de/blog'
import { Route as DeAboutRouteImport } from './routes/de/about'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as ArMediaRouteImport } from './routes/ar/media'
import { Route as ArIndustriesRouteImport } from './routes/ar/industries'
import { Route as ArExportRouteImport } from './routes/ar/export'
import { Route as ArContactRouteImport } from './routes/ar/contact'
import { Route as ArCatalogsRouteImport } from './routes/ar/catalogs'
import { Route as ArBlogRouteImport } from './routes/ar/blog'
import { Route as ArAboutRouteImport } from './routes/ar/about'
import { Route as TrProductsIndexRouteImport } from './routes/tr/products/index'
import { Route as RuProductsIndexRouteImport } from './routes/ru/products/index'
import { Route as FrProductsIndexRouteImport } from './routes/fr/products/index'
import { Route as FaProductsIndexRouteImport } from './routes/fa/products/index'
import { Route as DeProductsIndexRouteImport } from './routes/de/products/index'
import { Route as ArProductsIndexRouteImport } from './routes/ar/products/index'
import { Route as TrProductsYokohamaRouteImport } from './routes/tr/products/yokohama'
import { Route as TrProductsHiTechRouteImport } from './routes/tr/products/hi-tech'
import { Route as TrBlogSlugRouteImport } from './routes/tr/blog_.$slug'
import { Route as RuProductsYokohamaRouteImport } from './routes/ru/products/yokohama'
import { Route as RuProductsHiTechRouteImport } from './routes/ru/products/hi-tech'
import { Route as RuBlogSlugRouteImport } from './routes/ru/blog_.$slug'
import { Route as ProductsYokohamaCategoryRouteImport } from './routes/products/yokohama_.$category'
import { Route as ProductsHiTechCategoryRouteImport } from './routes/products/hi-tech_.$category'
import { Route as FrProductsYokohamaRouteImport } from './routes/fr/products/yokohama'
import { Route as FrProductsHiTechRouteImport } from './routes/fr/products/hi-tech'
import { Route as FrBlogSlugRouteImport } from './routes/fr/blog_.$slug'
import { Route as FaProductsYokohamaRouteImport } from './routes/fa/products/yokohama'
import { Route as FaProductsHiTechRouteImport } from './routes/fa/products/hi-tech'
import { Route as FaBlogSlugRouteImport } from './routes/fa/blog_.$slug'
import { Route as DeProductsYokohamaRouteImport } from './routes/de/products/yokohama'
import { Route as DeProductsHiTechRouteImport } from './routes/de/products/hi-tech'
import { Route as DeBlogSlugRouteImport } from './routes/de/blog_.$slug'
import { Route as ArProductsYokohamaRouteImport } from './routes/ar/products/yokohama'
import { Route as ArProductsHiTechRouteImport } from './routes/ar/products/hi-tech'
import { Route as ArBlogSlugRouteImport } from './routes/ar/blog_.$slug'
import { Route as TrProductsYokohamaCategoryRouteImport } from './routes/tr/products/yokohama_.$category'
import { Route as TrProductsHiTechCategoryRouteImport } from './routes/tr/products/hi-tech_.$category'
import { Route as RuProductsYokohamaCategoryRouteImport } from './routes/ru/products/yokohama_.$category'
import { Route as RuProductsHiTechCategoryRouteImport } from './routes/ru/products/hi-tech_.$category'
import { Route as ProductsYokohamaCategoryProductRouteImport } from './routes/products/yokohama_.$category.$product'
import { Route as ProductsHiTechCategoryProductRouteImport } from './routes/products/hi-tech_.$category.$product'
import { Route as FrProductsYokohamaCategoryRouteImport } from './routes/fr/products/yokohama_.$category'
import { Route as FrProductsHiTechCategoryRouteImport } from './routes/fr/products/hi-tech_.$category'
import { Route as FaProductsYokohamaCategoryRouteImport } from './routes/fa/products/yokohama_.$category'
import { Route as FaProductsHiTechCategoryRouteImport } from './routes/fa/products/hi-tech_.$category'
import { Route as DeProductsYokohamaCategoryRouteImport } from './routes/de/products/yokohama_.$category'
import { Route as DeProductsHiTechCategoryRouteImport } from './routes/de/products/hi-tech_.$category'
import { Route as ArProductsYokohamaCategoryRouteImport } from './routes/ar/products/yokohama_.$category'
import { Route as ArProductsHiTechCategoryRouteImport } from './routes/ar/products/hi-tech_.$category'
import { Route as TrProductsYokohamaCategoryProductRouteImport } from './routes/tr/products/yokohama_.$category.$product'
import { Route as TrProductsHiTechCategoryProductRouteImport } from './routes/tr/products/hi-tech_.$category.$product'
import { Route as RuProductsYokohamaCategoryProductRouteImport } from './routes/ru/products/yokohama_.$category.$product'
import { Route as RuProductsHiTechCategoryProductRouteImport } from './routes/ru/products/hi-tech_.$category.$product'
import { Route as FrProductsYokohamaCategoryProductRouteImport } from './routes/fr/products/yokohama_.$category.$product'
import { Route as FrProductsHiTechCategoryProductRouteImport } from './routes/fr/products/hi-tech_.$category.$product'
import { Route as FaProductsYokohamaCategoryProductRouteImport } from './routes/fa/products/yokohama_.$category.$product'
import { Route as FaProductsHiTechCategoryProductRouteImport } from './routes/fa/products/hi-tech_.$category.$product'
import { Route as DeProductsYokohamaCategoryProductRouteImport } from './routes/de/products/yokohama_.$category.$product'
import { Route as DeProductsHiTechCategoryProductRouteImport } from './routes/de/products/hi-tech_.$category.$product'
import { Route as ArProductsYokohamaCategoryProductRouteImport } from './routes/ar/products/yokohama_.$category.$product'
import { Route as ArProductsHiTechCategoryProductRouteImport } from './routes/ar/products/hi-tech_.$category.$product'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogsRoute = CatalogsRouteImport.update({
  id: '/catalogs',
  path: '/catalogs',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrIndexRoute = TrIndexRouteImport.update({
  id: '/tr/',
  path: '/tr/',
  getParentRoute: () => rootRouteImport,
} as any)
const RuIndexRoute = RuIndexRouteImport.update({
  id: '/ru/',
  path: '/ru/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrIndexRoute = FrIndexRouteImport.update({
  id: '/fr/',
  path: '/fr/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaIndexRoute = FaIndexRouteImport.update({
  id: '/fa/',
  path: '/fa/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeIndexRoute = DeIndexRouteImport.update({
  id: '/de/',
  path: '/de/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArIndexRoute = ArIndexRouteImport.update({
  id: '/ar/',
  path: '/ar/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrMediaRoute = TrMediaRouteImport.update({
  id: '/tr/media',
  path: '/tr/media',
  getParentRoute: () => rootRouteImport,
} as any)
const TrIndustriesRoute = TrIndustriesRouteImport.update({
  id: '/tr/industries',
  path: '/tr/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const TrExportRoute = TrExportRouteImport.update({
  id: '/tr/export',
  path: '/tr/export',
  getParentRoute: () => rootRouteImport,
} as any)
const TrContactRoute = TrContactRouteImport.update({
  id: '/tr/contact',
  path: '/tr/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const TrCatalogsRoute = TrCatalogsRouteImport.update({
  id: '/tr/catalogs',
  path: '/tr/catalogs',
  getParentRoute: () => rootRouteImport,
} as any)
const TrBlogRoute = TrBlogRouteImport.update({
  id: '/tr/blog',
  path: '/tr/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const TrAboutRoute = TrAboutRouteImport.update({
  id: '/tr/about',
  path: '/tr/about',
  getParentRoute: () => rootRouteImport,
} as any)
const RuMediaRoute = RuMediaRouteImport.update({
  id: '/ru/media',
  path: '/ru/media',
  getParentRoute: () => rootRouteImport,
} as any)
const RuIndustriesRoute = RuIndustriesRouteImport.update({
  id: '/ru/industries',
  path: '/ru/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const RuExportRoute = RuExportRouteImport.update({
  id: '/ru/export',
  path: '/ru/export',
  getParentRoute: () => rootRouteImport,
} as any)
const RuContactRoute = RuContactRouteImport.update({
  id: '/ru/contact',
  path: '/ru/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const RuCatalogsRoute = RuCatalogsRouteImport.update({
  id: '/ru/catalogs',
  path: '/ru/catalogs',
  getParentRoute: () => rootRouteImport,
} as any)
const RuBlogRoute = RuBlogRouteImport.update({
  id: '/ru/blog',
  path: '/ru/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const RuAboutRoute = RuAboutRouteImport.update({
  id: '/ru/about',
  path: '/ru/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsYokohamaRoute = ProductsYokohamaRouteImport.update({
  id: '/products/yokohama',
  path: '/products/yokohama',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsHiTechRoute = ProductsHiTechRouteImport.update({
  id: '/products/hi-tech',
  path: '/products/hi-tech',
  getParentRoute: () => rootRouteImport,
} as any)
const FrMediaRoute = FrMediaRouteImport.update({
  id: '/fr/media',
  path: '/fr/media',
  getParentRoute: () => rootRouteImport,
} as any)
const FrIndustriesRoute = FrIndustriesRouteImport.update({
  id: '/fr/industries',
  path: '/fr/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const FrExportRoute = FrExportRouteImport.update({
  id: '/fr/export',
  path: '/fr/export',
  getParentRoute: () => rootRouteImport,
} as any)
const FrContactRoute = FrContactRouteImport.update({
  id: '/fr/contact',
  path: '/fr/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FrCatalogsRoute = FrCatalogsRouteImport.update({
  id: '/fr/catalogs',
  path: '/fr/catalogs',
  getParentRoute: () => rootRouteImport,
} as any)
const FrBlogRoute = FrBlogRouteImport.update({
  id: '/fr/blog',
  path: '/fr/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const FrAboutRoute = FrAboutRouteImport.update({
  id: '/fr/about',
  path: '/fr/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FaMediaRoute = FaMediaRouteImport.update({
  id: '/fa/media',
  path: '/fa/media',
  getParentRoute: () => rootRouteImport,
} as any)
const FaIndustriesRoute = FaIndustriesRouteImport.update({
  id: '/fa/industries',
  path: '/fa/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const FaExportRoute = FaExportRouteImport.update({
  id: '/fa/export',
  path: '/fa/export',
  getParentRoute: () => rootRouteImport,
} as any)
const FaContactRoute = FaContactRouteImport.update({
  id: '/fa/contact',
  path: '/fa/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaCatalogsRoute = FaCatalogsRouteImport.update({
  id: '/fa/catalogs',
  path: '/fa/catalogs',
  getParentRoute: () => rootRouteImport,
} as any)
const FaBlogRoute = FaBlogRouteImport.update({
  id: '/fa/blog',
  path: '/fa/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const FaAboutRoute = FaAboutRouteImport.update({
  id: '/fa/about',
  path: '/fa/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DeMediaRoute = DeMediaRouteImport.update({
  id: '/de/media',
  path: '/de/media',
  getParentRoute: () => rootRouteImport,
} as any)
const DeIndustriesRoute = DeIndustriesRouteImport.update({
  id: '/de/industries',
  path: '/de/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const DeExportRoute = DeExportRouteImport.update({
  id: '/de/export',
  path: '/de/export',
  getParentRoute: () => rootRouteImport,
} as any)
const DeContactRoute = DeContactRouteImport.update({
  id: '/de/contact',
  path: '/de/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeCatalogsRoute = DeCatalogsRouteImport.update({
  id: '/de/catalogs',
  path: '/de/catalogs',
  getParentRoute: () => rootRouteImport,
} as any)
const DeBlogRoute = DeBlogRouteImport.update({
  id: '/de/blog',
  path: '/de/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const DeAboutRoute = DeAboutRouteImport.update({
  id: '/de/about',
  path: '/de/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArMediaRoute = ArMediaRouteImport.update({
  id: '/ar/media',
  path: '/ar/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ArIndustriesRoute = ArIndustriesRouteImport.update({
  id: '/ar/industries',
  path: '/ar/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ArExportRoute = ArExportRouteImport.update({
  id: '/ar/export',
  path: '/ar/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ArContactRoute = ArContactRouteImport.update({
  id: '/ar/contact',
  path: '/ar/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ArCatalogsRoute = ArCatalogsRouteImport.update({
  id: '/ar/catalogs',
  path: '/ar/catalogs',
  getParentRoute: () => rootRouteImport,
} as any)
const ArBlogRoute = ArBlogRouteImport.update({
  id: '/ar/blog',
  path: '/ar/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ArAboutRoute = ArAboutRouteImport.update({
  id: '/ar/about',
  path: '/ar/about',
  getParentRoute: () => rootRouteImport,
} as any)
const TrProductsIndexRoute = TrProductsIndexRouteImport.update({
  id: '/tr/products/',
  path: '/tr/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const RuProductsIndexRoute = RuProductsIndexRouteImport.update({
  id: '/ru/products/',
  path: '/ru/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrProductsIndexRoute = FrProductsIndexRouteImport.update({
  id: '/fr/products/',
  path: '/fr/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaProductsIndexRoute = FaProductsIndexRouteImport.update({
  id: '/fa/products/',
  path: '/fa/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeProductsIndexRoute = DeProductsIndexRouteImport.update({
  id: '/de/products/',
  path: '/de/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArProductsIndexRoute = ArProductsIndexRouteImport.update({
  id: '/ar/products/',
  path: '/ar/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrProductsYokohamaRoute = TrProductsYokohamaRouteImport.update({
  id: '/tr/products/yokohama',
  path: '/tr/products/yokohama',
  getParentRoute: () => rootRouteImport,
} as any)
const TrProductsHiTechRoute = TrProductsHiTechRouteImport.update({
  id: '/tr/products/hi-tech',
  path: '/tr/products/hi-tech',
  getParentRoute: () => rootRouteImport,
} as any)
const TrBlogSlugRoute = TrBlogSlugRouteImport.update({
  id: '/tr/blog_/$slug',
  path: '/tr/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RuProductsYokohamaRoute = RuProductsYokohamaRouteImport.update({
  id: '/ru/products/yokohama',
  path: '/ru/products/yokohama',
  getParentRoute: () => rootRouteImport,
} as any)
const RuProductsHiTechRoute = RuProductsHiTechRouteImport.update({
  id: '/ru/products/hi-tech',
  path: '/ru/products/hi-tech',
  getParentRoute: () => rootRouteImport,
} as any)
const RuBlogSlugRoute = RuBlogSlugRouteImport.update({
  id: '/ru/blog_/$slug',
  path: '/ru/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsYokohamaCategoryRoute =
  ProductsYokohamaCategoryRouteImport.update({
    id: '/products/yokohama_/$category',
    path: '/products/yokohama/$category',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsHiTechCategoryRoute = ProductsHiTechCategoryRouteImport.update({
  id: '/products/hi-tech_/$category',
  path: '/products/hi-tech/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const FrProductsYokohamaRoute = FrProductsYokohamaRouteImport.update({
  id: '/fr/products/yokohama',
  path: '/fr/products/yokohama',
  getParentRoute: () => rootRouteImport,
} as any)
const FrProductsHiTechRoute = FrProductsHiTechRouteImport.update({
  id: '/fr/products/hi-tech',
  path: '/fr/products/hi-tech',
  getParentRoute: () => rootRouteImport,
} as any)
const FrBlogSlugRoute = FrBlogSlugRouteImport.update({
  id: '/fr/blog_/$slug',
  path: '/fr/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FaProductsYokohamaRoute = FaProductsYokohamaRouteImport.update({
  id: '/fa/products/yokohama',
  path: '/fa/products/yokohama',
  getParentRoute: () => rootRouteImport,
} as any)
const FaProductsHiTechRoute = FaProductsHiTechRouteImport.update({
  id: '/fa/products/hi-tech',
  path: '/fa/products/hi-tech',
  getParentRoute: () => rootRouteImport,
} as any)
const FaBlogSlugRoute = FaBlogSlugRouteImport.update({
  id: '/fa/blog_/$slug',
  path: '/fa/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DeProductsYokohamaRoute = DeProductsYokohamaRouteImport.update({
  id: '/de/products/yokohama',
  path: '/de/products/yokohama',
  getParentRoute: () => rootRouteImport,
} as any)
const DeProductsHiTechRoute = DeProductsHiTechRouteImport.update({
  id: '/de/products/hi-tech',
  path: '/de/products/hi-tech',
  getParentRoute: () => rootRouteImport,
} as any)
const DeBlogSlugRoute = DeBlogSlugRouteImport.update({
  id: '/de/blog_/$slug',
  path: '/de/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArProductsYokohamaRoute = ArProductsYokohamaRouteImport.update({
  id: '/ar/products/yokohama',
  path: '/ar/products/yokohama',
  getParentRoute: () => rootRouteImport,
} as any)
const ArProductsHiTechRoute = ArProductsHiTechRouteImport.update({
  id: '/ar/products/hi-tech',
  path: '/ar/products/hi-tech',
  getParentRoute: () => rootRouteImport,
} as any)
const ArBlogSlugRoute = ArBlogSlugRouteImport.update({
  id: '/ar/blog_/$slug',
  path: '/ar/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TrProductsYokohamaCategoryRoute =
  TrProductsYokohamaCategoryRouteImport.update({
    id: '/tr/products/yokohama_/$category',
    path: '/tr/products/yokohama/$category',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrProductsHiTechCategoryRoute =
  TrProductsHiTechCategoryRouteImport.update({
    id: '/tr/products/hi-tech_/$category',
    path: '/tr/products/hi-tech/$category',
    getParentRoute: () => rootRouteImport,
  } as any)
const RuProductsYokohamaCategoryRoute =
  RuProductsYokohamaCategoryRouteImport.update({
    id: '/ru/products/yokohama_/$category',
    path: '/ru/products/yokohama/$category',
    getParentRoute: () => rootRouteImport,
  } as any)
const RuProductsHiTechCategoryRoute =
  RuProductsHiTechCategoryRouteImport.update({
    id: '/ru/products/hi-tech_/$category',
    path: '/ru/products/hi-tech/$category',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsYokohamaCategoryProductRoute =
  ProductsYokohamaCategoryProductRouteImport.update({
    id: '/$product',
    path: '/$product',
    getParentRoute: () => ProductsYokohamaCategoryRoute,
  } as any)
const ProductsHiTechCategoryProductRoute =
  ProductsHiTechCategoryProductRouteImport.update({
    id: '/$product',
    path: '/$product',
    getParentRoute: () => ProductsHiTechCategoryRoute,
  } as any)
const FrProductsYokohamaCategoryRoute =
  FrProductsYokohamaCategoryRouteImport.update({
    id: '/fr/products/yokohama_/$category',
    path: '/fr/products/yokohama/$category',
    getParentRoute: () => rootRouteImport,
  } as any)
const FrProductsHiTechCategoryRoute =
  FrProductsHiTechCategoryRouteImport.update({
    id: '/fr/products/hi-tech_/$category',
    path: '/fr/products/hi-tech/$category',
    getParentRoute: () => rootRouteImport,
  } as any)
const FaProductsYokohamaCategoryRoute =
  FaProductsYokohamaCategoryRouteImport.update({
    id: '/fa/products/yokohama_/$category',
    path: '/fa/products/yokohama/$category',
    getParentRoute: () => rootRouteImport,
  } as any)
const FaProductsHiTechCategoryRoute =
  FaProductsHiTechCategoryRouteImport.update({
    id: '/fa/products/hi-tech_/$category',
    path: '/fa/products/hi-tech/$category',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeProductsYokohamaCategoryRoute =
  DeProductsYokohamaCategoryRouteImport.update({
    id: '/de/products/yokohama_/$category',
    path: '/de/products/yokohama/$category',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeProductsHiTechCategoryRoute =
  DeProductsHiTechCategoryRouteImport.update({
    id: '/de/products/hi-tech_/$category',
    path: '/de/products/hi-tech/$category',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArProductsYokohamaCategoryRoute =
  ArProductsYokohamaCategoryRouteImport.update({
    id: '/ar/products/yokohama_/$category',
    path: '/ar/products/yokohama/$category',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArProductsHiTechCategoryRoute =
  ArProductsHiTechCategoryRouteImport.update({
    id: '/ar/products/hi-tech_/$category',
    path: '/ar/products/hi-tech/$category',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrProductsYokohamaCategoryProductRoute =
  TrProductsYokohamaCategoryProductRouteImport.update({
    id: '/$product',
    path: '/$product',
    getParentRoute: () => TrProductsYokohamaCategoryRoute,
  } as any)
const TrProductsHiTechCategoryProductRoute =
  TrProductsHiTechCategoryProductRouteImport.update({
    id: '/$product',
    path: '/$product',
    getParentRoute: () => TrProductsHiTechCategoryRoute,
  } as any)
const RuProductsYokohamaCategoryProductRoute =
  RuProductsYokohamaCategoryProductRouteImport.update({
    id: '/$product',
    path: '/$product',
    getParentRoute: () => RuProductsYokohamaCategoryRoute,
  } as any)
const RuProductsHiTechCategoryProductRoute =
  RuProductsHiTechCategoryProductRouteImport.update({
    id: '/$product',
    path: '/$product',
    getParentRoute: () => RuProductsHiTechCategoryRoute,
  } as any)
const FrProductsYokohamaCategoryProductRoute =
  FrProductsYokohamaCategoryProductRouteImport.update({
    id: '/$product',
    path: '/$product',
    getParentRoute: () => FrProductsYokohamaCategoryRoute,
  } as any)
const FrProductsHiTechCategoryProductRoute =
  FrProductsHiTechCategoryProductRouteImport.update({
    id: '/$product',
    path: '/$product',
    getParentRoute: () => FrProductsHiTechCategoryRoute,
  } as any)
const FaProductsYokohamaCategoryProductRoute =
  FaProductsYokohamaCategoryProductRouteImport.update({
    id: '/$product',
    path: '/$product',
    getParentRoute: () => FaProductsYokohamaCategoryRoute,
  } as any)
const FaProductsHiTechCategoryProductRoute =
  FaProductsHiTechCategoryProductRouteImport.update({
    id: '/$product',
    path: '/$product',
    getParentRoute: () => FaProductsHiTechCategoryRoute,
  } as any)
const DeProductsYokohamaCategoryProductRoute =
  DeProductsYokohamaCategoryProductRouteImport.update({
    id: '/$product',
    path: '/$product',
    getParentRoute: () => DeProductsYokohamaCategoryRoute,
  } as any)
const DeProductsHiTechCategoryProductRoute =
  DeProductsHiTechCategoryProductRouteImport.update({
    id: '/$product',
    path: '/$product',
    getParentRoute: () => DeProductsHiTechCategoryRoute,
  } as any)
const ArProductsYokohamaCategoryProductRoute =
  ArProductsYokohamaCategoryProductRouteImport.update({
    id: '/$product',
    path: '/$product',
    getParentRoute: () => ArProductsYokohamaCategoryRoute,
  } as any)
const ArProductsHiTechCategoryProductRoute =
  ArProductsHiTechCategoryProductRouteImport.update({
    id: '/$product',
    path: '/$product',
    getParentRoute: () => ArProductsHiTechCategoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/catalogs': typeof CatalogsRoute
  '/contact': typeof ContactRoute
  '/export': typeof ExportRoute
  '/industries': typeof IndustriesRoute
  '/media': typeof MediaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ar/about': typeof ArAboutRoute
  '/ar/blog': typeof ArBlogRoute
  '/ar/catalogs': typeof ArCatalogsRoute
  '/ar/contact': typeof ArContactRoute
  '/ar/export': typeof ArExportRoute
  '/ar/industries': typeof ArIndustriesRoute
  '/ar/media': typeof ArMediaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/de/about': typeof DeAboutRoute
  '/de/blog': typeof DeBlogRoute
  '/de/catalogs': typeof DeCatalogsRoute
  '/de/contact': typeof DeContactRoute
  '/de/export': typeof DeExportRoute
  '/de/industries': typeof DeIndustriesRoute
  '/de/media': typeof DeMediaRoute
  '/fa/about': typeof FaAboutRoute
  '/fa/blog': typeof FaBlogRoute
  '/fa/catalogs': typeof FaCatalogsRoute
  '/fa/contact': typeof FaContactRoute
  '/fa/export': typeof FaExportRoute
  '/fa/industries': typeof FaIndustriesRoute
  '/fa/media': typeof FaMediaRoute
  '/fr/about': typeof FrAboutRoute
  '/fr/blog': typeof FrBlogRoute
  '/fr/catalogs': typeof FrCatalogsRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/export': typeof FrExportRoute
  '/fr/industries': typeof FrIndustriesRoute
  '/fr/media': typeof FrMediaRoute
  '/products/hi-tech': typeof ProductsHiTechRoute
  '/products/yokohama': typeof ProductsYokohamaRoute
  '/ru/about': typeof RuAboutRoute
  '/ru/blog': typeof RuBlogRoute
  '/ru/catalogs': typeof RuCatalogsRoute
  '/ru/contact': typeof RuContactRoute
  '/ru/export': typeof RuExportRoute
  '/ru/industries': typeof RuIndustriesRoute
  '/ru/media': typeof RuMediaRoute
  '/tr/about': typeof TrAboutRoute
  '/tr/blog': typeof TrBlogRoute
  '/tr/catalogs': typeof TrCatalogsRoute
  '/tr/contact': typeof TrContactRoute
  '/tr/export': typeof TrExportRoute
  '/tr/industries': typeof TrIndustriesRoute
  '/tr/media': typeof TrMediaRoute
  '/ar/': typeof ArIndexRoute
  '/de/': typeof DeIndexRoute
  '/fa/': typeof FaIndexRoute
  '/fr/': typeof FrIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/ru/': typeof RuIndexRoute
  '/tr/': typeof TrIndexRoute
  '/ar/blog/$slug': typeof ArBlogSlugRoute
  '/ar/products/hi-tech': typeof ArProductsHiTechRoute
  '/ar/products/yokohama': typeof ArProductsYokohamaRoute
  '/de/blog/$slug': typeof DeBlogSlugRoute
  '/de/products/hi-tech': typeof DeProductsHiTechRoute
  '/de/products/yokohama': typeof DeProductsYokohamaRoute
  '/fa/blog/$slug': typeof FaBlogSlugRoute
  '/fa/products/hi-tech': typeof FaProductsHiTechRoute
  '/fa/products/yokohama': typeof FaProductsYokohamaRoute
  '/fr/blog/$slug': typeof FrBlogSlugRoute
  '/fr/products/hi-tech': typeof FrProductsHiTechRoute
  '/fr/products/yokohama': typeof FrProductsYokohamaRoute
  '/products/hi-tech/$category': typeof ProductsHiTechCategoryRouteWithChildren
  '/products/yokohama/$category': typeof ProductsYokohamaCategoryRouteWithChildren
  '/ru/blog/$slug': typeof RuBlogSlugRoute
  '/ru/products/hi-tech': typeof RuProductsHiTechRoute
  '/ru/products/yokohama': typeof RuProductsYokohamaRoute
  '/tr/blog/$slug': typeof TrBlogSlugRoute
  '/tr/products/hi-tech': typeof TrProductsHiTechRoute
  '/tr/products/yokohama': typeof TrProductsYokohamaRoute
  '/ar/products/': typeof ArProductsIndexRoute
  '/de/products/': typeof DeProductsIndexRoute
  '/fa/products/': typeof FaProductsIndexRoute
  '/fr/products/': typeof FrProductsIndexRoute
  '/ru/products/': typeof RuProductsIndexRoute
  '/tr/products/': typeof TrProductsIndexRoute
  '/ar/products/hi-tech/$category': typeof ArProductsHiTechCategoryRouteWithChildren
  '/ar/products/yokohama/$category': typeof ArProductsYokohamaCategoryRouteWithChildren
  '/de/products/hi-tech/$category': typeof DeProductsHiTechCategoryRouteWithChildren
  '/de/products/yokohama/$category': typeof DeProductsYokohamaCategoryRouteWithChildren
  '/fa/products/hi-tech/$category': typeof FaProductsHiTechCategoryRouteWithChildren
  '/fa/products/yokohama/$category': typeof FaProductsYokohamaCategoryRouteWithChildren
  '/fr/products/hi-tech/$category': typeof FrProductsHiTechCategoryRouteWithChildren
  '/fr/products/yokohama/$category': typeof FrProductsYokohamaCategoryRouteWithChildren
  '/products/hi-tech/$category/$product': typeof ProductsHiTechCategoryProductRoute
  '/products/yokohama/$category/$product': typeof ProductsYokohamaCategoryProductRoute
  '/ru/products/hi-tech/$category': typeof RuProductsHiTechCategoryRouteWithChildren
  '/ru/products/yokohama/$category': typeof RuProductsYokohamaCategoryRouteWithChildren
  '/tr/products/hi-tech/$category': typeof TrProductsHiTechCategoryRouteWithChildren
  '/tr/products/yokohama/$category': typeof TrProductsYokohamaCategoryRouteWithChildren
  '/ar/products/hi-tech/$category/$product': typeof ArProductsHiTechCategoryProductRoute
  '/ar/products/yokohama/$category/$product': typeof ArProductsYokohamaCategoryProductRoute
  '/de/products/hi-tech/$category/$product': typeof DeProductsHiTechCategoryProductRoute
  '/de/products/yokohama/$category/$product': typeof DeProductsYokohamaCategoryProductRoute
  '/fa/products/hi-tech/$category/$product': typeof FaProductsHiTechCategoryProductRoute
  '/fa/products/yokohama/$category/$product': typeof FaProductsYokohamaCategoryProductRoute
  '/fr/products/hi-tech/$category/$product': typeof FrProductsHiTechCategoryProductRoute
  '/fr/products/yokohama/$category/$product': typeof FrProductsYokohamaCategoryProductRoute
  '/ru/products/hi-tech/$category/$product': typeof RuProductsHiTechCategoryProductRoute
  '/ru/products/yokohama/$category/$product': typeof RuProductsYokohamaCategoryProductRoute
  '/tr/products/hi-tech/$category/$product': typeof TrProductsHiTechCategoryProductRoute
  '/tr/products/yokohama/$category/$product': typeof TrProductsYokohamaCategoryProductRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/catalogs': typeof CatalogsRoute
  '/contact': typeof ContactRoute
  '/export': typeof ExportRoute
  '/industries': typeof IndustriesRoute
  '/media': typeof MediaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ar/about': typeof ArAboutRoute
  '/ar/blog': typeof ArBlogRoute
  '/ar/catalogs': typeof ArCatalogsRoute
  '/ar/contact': typeof ArContactRoute
  '/ar/export': typeof ArExportRoute
  '/ar/industries': typeof ArIndustriesRoute
  '/ar/media': typeof ArMediaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/de/about': typeof DeAboutRoute
  '/de/blog': typeof DeBlogRoute
  '/de/catalogs': typeof DeCatalogsRoute
  '/de/contact': typeof DeContactRoute
  '/de/export': typeof DeExportRoute
  '/de/industries': typeof DeIndustriesRoute
  '/de/media': typeof DeMediaRoute
  '/fa/about': typeof FaAboutRoute
  '/fa/blog': typeof FaBlogRoute
  '/fa/catalogs': typeof FaCatalogsRoute
  '/fa/contact': typeof FaContactRoute
  '/fa/export': typeof FaExportRoute
  '/fa/industries': typeof FaIndustriesRoute
  '/fa/media': typeof FaMediaRoute
  '/fr/about': typeof FrAboutRoute
  '/fr/blog': typeof FrBlogRoute
  '/fr/catalogs': typeof FrCatalogsRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/export': typeof FrExportRoute
  '/fr/industries': typeof FrIndustriesRoute
  '/fr/media': typeof FrMediaRoute
  '/products/hi-tech': typeof ProductsHiTechRoute
  '/products/yokohama': typeof ProductsYokohamaRoute
  '/ru/about': typeof RuAboutRoute
  '/ru/blog': typeof RuBlogRoute
  '/ru/catalogs': typeof RuCatalogsRoute
  '/ru/contact': typeof RuContactRoute
  '/ru/export': typeof RuExportRoute
  '/ru/industries': typeof RuIndustriesRoute
  '/ru/media': typeof RuMediaRoute
  '/tr/about': typeof TrAboutRoute
  '/tr/blog': typeof TrBlogRoute
  '/tr/catalogs': typeof TrCatalogsRoute
  '/tr/contact': typeof TrContactRoute
  '/tr/export': typeof TrExportRoute
  '/tr/industries': typeof TrIndustriesRoute
  '/tr/media': typeof TrMediaRoute
  '/ar': typeof ArIndexRoute
  '/de': typeof DeIndexRoute
  '/fa': typeof FaIndexRoute
  '/fr': typeof FrIndexRoute
  '/products': typeof ProductsIndexRoute
  '/ru': typeof RuIndexRoute
  '/tr': typeof TrIndexRoute
  '/ar/blog/$slug': typeof ArBlogSlugRoute
  '/ar/products/hi-tech': typeof ArProductsHiTechRoute
  '/ar/products/yokohama': typeof ArProductsYokohamaRoute
  '/de/blog/$slug': typeof DeBlogSlugRoute
  '/de/products/hi-tech': typeof DeProductsHiTechRoute
  '/de/products/yokohama': typeof DeProductsYokohamaRoute
  '/fa/blog/$slug': typeof FaBlogSlugRoute
  '/fa/products/hi-tech': typeof FaProductsHiTechRoute
  '/fa/products/yokohama': typeof FaProductsYokohamaRoute
  '/fr/blog/$slug': typeof FrBlogSlugRoute
  '/fr/products/hi-tech': typeof FrProductsHiTechRoute
  '/fr/products/yokohama': typeof FrProductsYokohamaRoute
  '/products/hi-tech/$category': typeof ProductsHiTechCategoryRouteWithChildren
  '/products/yokohama/$category': typeof ProductsYokohamaCategoryRouteWithChildren
  '/ru/blog/$slug': typeof RuBlogSlugRoute
  '/ru/products/hi-tech': typeof RuProductsHiTechRoute
  '/ru/products/yokohama': typeof RuProductsYokohamaRoute
  '/tr/blog/$slug': typeof TrBlogSlugRoute
  '/tr/products/hi-tech': typeof TrProductsHiTechRoute
  '/tr/products/yokohama': typeof TrProductsYokohamaRoute
  '/ar/products': typeof ArProductsIndexRoute
  '/de/products': typeof DeProductsIndexRoute
  '/fa/products': typeof FaProductsIndexRoute
  '/fr/products': typeof FrProductsIndexRoute
  '/ru/products': typeof RuProductsIndexRoute
  '/tr/products': typeof TrProductsIndexRoute
  '/ar/products/hi-tech/$category': typeof ArProductsHiTechCategoryRouteWithChildren
  '/ar/products/yokohama/$category': typeof ArProductsYokohamaCategoryRouteWithChildren
  '/de/products/hi-tech/$category': typeof DeProductsHiTechCategoryRouteWithChildren
  '/de/products/yokohama/$category': typeof DeProductsYokohamaCategoryRouteWithChildren
  '/fa/products/hi-tech/$category': typeof FaProductsHiTechCategoryRouteWithChildren
  '/fa/products/yokohama/$category': typeof FaProductsYokohamaCategoryRouteWithChildren
  '/fr/products/hi-tech/$category': typeof FrProductsHiTechCategoryRouteWithChildren
  '/fr/products/yokohama/$category': typeof FrProductsYokohamaCategoryRouteWithChildren
  '/products/hi-tech/$category/$product': typeof ProductsHiTechCategoryProductRoute
  '/products/yokohama/$category/$product': typeof ProductsYokohamaCategoryProductRoute
  '/ru/products/hi-tech/$category': typeof RuProductsHiTechCategoryRouteWithChildren
  '/ru/products/yokohama/$category': typeof RuProductsYokohamaCategoryRouteWithChildren
  '/tr/products/hi-tech/$category': typeof TrProductsHiTechCategoryRouteWithChildren
  '/tr/products/yokohama/$category': typeof TrProductsYokohamaCategoryRouteWithChildren
  '/ar/products/hi-tech/$category/$product': typeof ArProductsHiTechCategoryProductRoute
  '/ar/products/yokohama/$category/$product': typeof ArProductsYokohamaCategoryProductRoute
  '/de/products/hi-tech/$category/$product': typeof DeProductsHiTechCategoryProductRoute
  '/de/products/yokohama/$category/$product': typeof DeProductsYokohamaCategoryProductRoute
  '/fa/products/hi-tech/$category/$product': typeof FaProductsHiTechCategoryProductRoute
  '/fa/products/yokohama/$category/$product': typeof FaProductsYokohamaCategoryProductRoute
  '/fr/products/hi-tech/$category/$product': typeof FrProductsHiTechCategoryProductRoute
  '/fr/products/yokohama/$category/$product': typeof FrProductsYokohamaCategoryProductRoute
  '/ru/products/hi-tech/$category/$product': typeof RuProductsHiTechCategoryProductRoute
  '/ru/products/yokohama/$category/$product': typeof RuProductsYokohamaCategoryProductRoute
  '/tr/products/hi-tech/$category/$product': typeof TrProductsHiTechCategoryProductRoute
  '/tr/products/yokohama/$category/$product': typeof TrProductsYokohamaCategoryProductRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/catalogs': typeof CatalogsRoute
  '/contact': typeof ContactRoute
  '/export': typeof ExportRoute
  '/industries': typeof IndustriesRoute
  '/media': typeof MediaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ar/about': typeof ArAboutRoute
  '/ar/blog': typeof ArBlogRoute
  '/ar/catalogs': typeof ArCatalogsRoute
  '/ar/contact': typeof ArContactRoute
  '/ar/export': typeof ArExportRoute
  '/ar/industries': typeof ArIndustriesRoute
  '/ar/media': typeof ArMediaRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/de/about': typeof DeAboutRoute
  '/de/blog': typeof DeBlogRoute
  '/de/catalogs': typeof DeCatalogsRoute
  '/de/contact': typeof DeContactRoute
  '/de/export': typeof DeExportRoute
  '/de/industries': typeof DeIndustriesRoute
  '/de/media': typeof DeMediaRoute
  '/fa/about': typeof FaAboutRoute
  '/fa/blog': typeof FaBlogRoute
  '/fa/catalogs': typeof FaCatalogsRoute
  '/fa/contact': typeof FaContactRoute
  '/fa/export': typeof FaExportRoute
  '/fa/industries': typeof FaIndustriesRoute
  '/fa/media': typeof FaMediaRoute
  '/fr/about': typeof FrAboutRoute
  '/fr/blog': typeof FrBlogRoute
  '/fr/catalogs': typeof FrCatalogsRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/export': typeof FrExportRoute
  '/fr/industries': typeof FrIndustriesRoute
  '/fr/media': typeof FrMediaRoute
  '/products/hi-tech': typeof ProductsHiTechRoute
  '/products/yokohama': typeof ProductsYokohamaRoute
  '/ru/about': typeof RuAboutRoute
  '/ru/blog': typeof RuBlogRoute
  '/ru/catalogs': typeof RuCatalogsRoute
  '/ru/contact': typeof RuContactRoute
  '/ru/export': typeof RuExportRoute
  '/ru/industries': typeof RuIndustriesRoute
  '/ru/media': typeof RuMediaRoute
  '/tr/about': typeof TrAboutRoute
  '/tr/blog': typeof TrBlogRoute
  '/tr/catalogs': typeof TrCatalogsRoute
  '/tr/contact': typeof TrContactRoute
  '/tr/export': typeof TrExportRoute
  '/tr/industries': typeof TrIndustriesRoute
  '/tr/media': typeof TrMediaRoute
  '/ar/': typeof ArIndexRoute
  '/de/': typeof DeIndexRoute
  '/fa/': typeof FaIndexRoute
  '/fr/': typeof FrIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/ru/': typeof RuIndexRoute
  '/tr/': typeof TrIndexRoute
  '/ar/blog_/$slug': typeof ArBlogSlugRoute
  '/ar/products/hi-tech': typeof ArProductsHiTechRoute
  '/ar/products/yokohama': typeof ArProductsYokohamaRoute
  '/de/blog_/$slug': typeof DeBlogSlugRoute
  '/de/products/hi-tech': typeof DeProductsHiTechRoute
  '/de/products/yokohama': typeof DeProductsYokohamaRoute
  '/fa/blog_/$slug': typeof FaBlogSlugRoute
  '/fa/products/hi-tech': typeof FaProductsHiTechRoute
  '/fa/products/yokohama': typeof FaProductsYokohamaRoute
  '/fr/blog_/$slug': typeof FrBlogSlugRoute
  '/fr/products/hi-tech': typeof FrProductsHiTechRoute
  '/fr/products/yokohama': typeof FrProductsYokohamaRoute
  '/products/hi-tech_/$category': typeof ProductsHiTechCategoryRouteWithChildren
  '/products/yokohama_/$category': typeof ProductsYokohamaCategoryRouteWithChildren
  '/ru/blog_/$slug': typeof RuBlogSlugRoute
  '/ru/products/hi-tech': typeof RuProductsHiTechRoute
  '/ru/products/yokohama': typeof RuProductsYokohamaRoute
  '/tr/blog_/$slug': typeof TrBlogSlugRoute
  '/tr/products/hi-tech': typeof TrProductsHiTechRoute
  '/tr/products/yokohama': typeof TrProductsYokohamaRoute
  '/ar/products/': typeof ArProductsIndexRoute
  '/de/products/': typeof DeProductsIndexRoute
  '/fa/products/': typeof FaProductsIndexRoute
  '/fr/products/': typeof FrProductsIndexRoute
  '/ru/products/': typeof RuProductsIndexRoute
  '/tr/products/': typeof TrProductsIndexRoute
  '/ar/products/hi-tech_/$category': typeof ArProductsHiTechCategoryRouteWithChildren
  '/ar/products/yokohama_/$category': typeof ArProductsYokohamaCategoryRouteWithChildren
  '/de/products/hi-tech_/$category': typeof DeProductsHiTechCategoryRouteWithChildren
  '/de/products/yokohama_/$category': typeof DeProductsYokohamaCategoryRouteWithChildren
  '/fa/products/hi-tech_/$category': typeof FaProductsHiTechCategoryRouteWithChildren
  '/fa/products/yokohama_/$category': typeof FaProductsYokohamaCategoryRouteWithChildren
  '/fr/products/hi-tech_/$category': typeof FrProductsHiTechCategoryRouteWithChildren
  '/fr/products/yokohama_/$category': typeof FrProductsYokohamaCategoryRouteWithChildren
  '/products/hi-tech_/$category/$product': typeof ProductsHiTechCategoryProductRoute
  '/products/yokohama_/$category/$product': typeof ProductsYokohamaCategoryProductRoute
  '/ru/products/hi-tech_/$category': typeof RuProductsHiTechCategoryRouteWithChildren
  '/ru/products/yokohama_/$category': typeof RuProductsYokohamaCategoryRouteWithChildren
  '/tr/products/hi-tech_/$category': typeof TrProductsHiTechCategoryRouteWithChildren
  '/tr/products/yokohama_/$category': typeof TrProductsYokohamaCategoryRouteWithChildren
  '/ar/products/hi-tech_/$category/$product': typeof ArProductsHiTechCategoryProductRoute
  '/ar/products/yokohama_/$category/$product': typeof ArProductsYokohamaCategoryProductRoute
  '/de/products/hi-tech_/$category/$product': typeof DeProductsHiTechCategoryProductRoute
  '/de/products/yokohama_/$category/$product': typeof DeProductsYokohamaCategoryProductRoute
  '/fa/products/hi-tech_/$category/$product': typeof FaProductsHiTechCategoryProductRoute
  '/fa/products/yokohama_/$category/$product': typeof FaProductsYokohamaCategoryProductRoute
  '/fr/products/hi-tech_/$category/$product': typeof FrProductsHiTechCategoryProductRoute
  '/fr/products/yokohama_/$category/$product': typeof FrProductsYokohamaCategoryProductRoute
  '/ru/products/hi-tech_/$category/$product': typeof RuProductsHiTechCategoryProductRoute
  '/ru/products/yokohama_/$category/$product': typeof RuProductsYokohamaCategoryProductRoute
  '/tr/products/hi-tech_/$category/$product': typeof TrProductsHiTechCategoryProductRoute
  '/tr/products/yokohama_/$category/$product': typeof TrProductsYokohamaCategoryProductRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/catalogs'
    | '/contact'
    | '/export'
    | '/industries'
    | '/media'
    | '/sitemap.xml'
    | '/ar/about'
    | '/ar/blog'
    | '/ar/catalogs'
    | '/ar/contact'
    | '/ar/export'
    | '/ar/industries'
    | '/ar/media'
    | '/blog/$slug'
    | '/de/about'
    | '/de/blog'
    | '/de/catalogs'
    | '/de/contact'
    | '/de/export'
    | '/de/industries'
    | '/de/media'
    | '/fa/about'
    | '/fa/blog'
    | '/fa/catalogs'
    | '/fa/contact'
    | '/fa/export'
    | '/fa/industries'
    | '/fa/media'
    | '/fr/about'
    | '/fr/blog'
    | '/fr/catalogs'
    | '/fr/contact'
    | '/fr/export'
    | '/fr/industries'
    | '/fr/media'
    | '/products/hi-tech'
    | '/products/yokohama'
    | '/ru/about'
    | '/ru/blog'
    | '/ru/catalogs'
    | '/ru/contact'
    | '/ru/export'
    | '/ru/industries'
    | '/ru/media'
    | '/tr/about'
    | '/tr/blog'
    | '/tr/catalogs'
    | '/tr/contact'
    | '/tr/export'
    | '/tr/industries'
    | '/tr/media'
    | '/ar/'
    | '/de/'
    | '/fa/'
    | '/fr/'
    | '/products/'
    | '/ru/'
    | '/tr/'
    | '/ar/blog/$slug'
    | '/ar/products/hi-tech'
    | '/ar/products/yokohama'
    | '/de/blog/$slug'
    | '/de/products/hi-tech'
    | '/de/products/yokohama'
    | '/fa/blog/$slug'
    | '/fa/products/hi-tech'
    | '/fa/products/yokohama'
    | '/fr/blog/$slug'
    | '/fr/products/hi-tech'
    | '/fr/products/yokohama'
    | '/products/hi-tech/$category'
    | '/products/yokohama/$category'
    | '/ru/blog/$slug'
    | '/ru/products/hi-tech'
    | '/ru/products/yokohama'
    | '/tr/blog/$slug'
    | '/tr/products/hi-tech'
    | '/tr/products/yokohama'
    | '/ar/products/'
    | '/de/products/'
    | '/fa/products/'
    | '/fr/products/'
    | '/ru/products/'
    | '/tr/products/'
    | '/ar/products/hi-tech/$category'
    | '/ar/products/yokohama/$category'
    | '/de/products/hi-tech/$category'
    | '/de/products/yokohama/$category'
    | '/fa/products/hi-tech/$category'
    | '/fa/products/yokohama/$category'
    | '/fr/products/hi-tech/$category'
    | '/fr/products/yokohama/$category'
    | '/products/hi-tech/$category/$product'
    | '/products/yokohama/$category/$product'
    | '/ru/products/hi-tech/$category'
    | '/ru/products/yokohama/$category'
    | '/tr/products/hi-tech/$category'
    | '/tr/products/yokohama/$category'
    | '/ar/products/hi-tech/$category/$product'
    | '/ar/products/yokohama/$category/$product'
    | '/de/products/hi-tech/$category/$product'
    | '/de/products/yokohama/$category/$product'
    | '/fa/products/hi-tech/$category/$product'
    | '/fa/products/yokohama/$category/$product'
    | '/fr/products/hi-tech/$category/$product'
    | '/fr/products/yokohama/$category/$product'
    | '/ru/products/hi-tech/$category/$product'
    | '/ru/products/yokohama/$category/$product'
    | '/tr/products/hi-tech/$category/$product'
    | '/tr/products/yokohama/$category/$product'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/catalogs'
    | '/contact'
    | '/export'
    | '/industries'
    | '/media'
    | '/sitemap.xml'
    | '/ar/about'
    | '/ar/blog'
    | '/ar/catalogs'
    | '/ar/contact'
    | '/ar/export'
    | '/ar/industries'
    | '/ar/media'
    | '/blog/$slug'
    | '/de/about'
    | '/de/blog'
    | '/de/catalogs'
    | '/de/contact'
    | '/de/export'
    | '/de/industries'
    | '/de/media'
    | '/fa/about'
    | '/fa/blog'
    | '/fa/catalogs'
    | '/fa/contact'
    | '/fa/export'
    | '/fa/industries'
    | '/fa/media'
    | '/fr/about'
    | '/fr/blog'
    | '/fr/catalogs'
    | '/fr/contact'
    | '/fr/export'
    | '/fr/industries'
    | '/fr/media'
    | '/products/hi-tech'
    | '/products/yokohama'
    | '/ru/about'
    | '/ru/blog'
    | '/ru/catalogs'
    | '/ru/contact'
    | '/ru/export'
    | '/ru/industries'
    | '/ru/media'
    | '/tr/about'
    | '/tr/blog'
    | '/tr/catalogs'
    | '/tr/contact'
    | '/tr/export'
    | '/tr/industries'
    | '/tr/media'
    | '/ar'
    | '/de'
    | '/fa'
    | '/fr'
    | '/products'
    | '/ru'
    | '/tr'
    | '/ar/blog/$slug'
    | '/ar/products/hi-tech'
    | '/ar/products/yokohama'
    | '/de/blog/$slug'
    | '/de/products/hi-tech'
    | '/de/products/yokohama'
    | '/fa/blog/$slug'
    | '/fa/products/hi-tech'
    | '/fa/products/yokohama'
    | '/fr/blog/$slug'
    | '/fr/products/hi-tech'
    | '/fr/products/yokohama'
    | '/products/hi-tech/$category'
    | '/products/yokohama/$category'
    | '/ru/blog/$slug'
    | '/ru/products/hi-tech'
    | '/ru/products/yokohama'
    | '/tr/blog/$slug'
    | '/tr/products/hi-tech'
    | '/tr/products/yokohama'
    | '/ar/products'
    | '/de/products'
    | '/fa/products'
    | '/fr/products'
    | '/ru/products'
    | '/tr/products'
    | '/ar/products/hi-tech/$category'
    | '/ar/products/yokohama/$category'
    | '/de/products/hi-tech/$category'
    | '/de/products/yokohama/$category'
    | '/fa/products/hi-tech/$category'
    | '/fa/products/yokohama/$category'
    | '/fr/products/hi-tech/$category'
    | '/fr/products/yokohama/$category'
    | '/products/hi-tech/$category/$product'
    | '/products/yokohama/$category/$product'
    | '/ru/products/hi-tech/$category'
    | '/ru/products/yokohama/$category'
    | '/tr/products/hi-tech/$category'
    | '/tr/products/yokohama/$category'
    | '/ar/products/hi-tech/$category/$product'
    | '/ar/products/yokohama/$category/$product'
    | '/de/products/hi-tech/$category/$product'
    | '/de/products/yokohama/$category/$product'
    | '/fa/products/hi-tech/$category/$product'
    | '/fa/products/yokohama/$category/$product'
    | '/fr/products/hi-tech/$category/$product'
    | '/fr/products/yokohama/$category/$product'
    | '/ru/products/hi-tech/$category/$product'
    | '/ru/products/yokohama/$category/$product'
    | '/tr/products/hi-tech/$category/$product'
    | '/tr/products/yokohama/$category/$product'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/catalogs'
    | '/contact'
    | '/export'
    | '/industries'
    | '/media'
    | '/sitemap.xml'
    | '/ar/about'
    | '/ar/blog'
    | '/ar/catalogs'
    | '/ar/contact'
    | '/ar/export'
    | '/ar/industries'
    | '/ar/media'
    | '/blog_/$slug'
    | '/de/about'
    | '/de/blog'
    | '/de/catalogs'
    | '/de/contact'
    | '/de/export'
    | '/de/industries'
    | '/de/media'
    | '/fa/about'
    | '/fa/blog'
    | '/fa/catalogs'
    | '/fa/contact'
    | '/fa/export'
    | '/fa/industries'
    | '/fa/media'
    | '/fr/about'
    | '/fr/blog'
    | '/fr/catalogs'
    | '/fr/contact'
    | '/fr/export'
    | '/fr/industries'
    | '/fr/media'
    | '/products/hi-tech'
    | '/products/yokohama'
    | '/ru/about'
    | '/ru/blog'
    | '/ru/catalogs'
    | '/ru/contact'
    | '/ru/export'
    | '/ru/industries'
    | '/ru/media'
    | '/tr/about'
    | '/tr/blog'
    | '/tr/catalogs'
    | '/tr/contact'
    | '/tr/export'
    | '/tr/industries'
    | '/tr/media'
    | '/ar/'
    | '/de/'
    | '/fa/'
    | '/fr/'
    | '/products/'
    | '/ru/'
    | '/tr/'
    | '/ar/blog_/$slug'
    | '/ar/products/hi-tech'
    | '/ar/products/yokohama'
    | '/de/blog_/$slug'
    | '/de/products/hi-tech'
    | '/de/products/yokohama'
    | '/fa/blog_/$slug'
    | '/fa/products/hi-tech'
    | '/fa/products/yokohama'
    | '/fr/blog_/$slug'
    | '/fr/products/hi-tech'
    | '/fr/products/yokohama'
    | '/products/hi-tech_/$category'
    | '/products/yokohama_/$category'
    | '/ru/blog_/$slug'
    | '/ru/products/hi-tech'
    | '/ru/products/yokohama'
    | '/tr/blog_/$slug'
    | '/tr/products/hi-tech'
    | '/tr/products/yokohama'
    | '/ar/products/'
    | '/de/products/'
    | '/fa/products/'
    | '/fr/products/'
    | '/ru/products/'
    | '/tr/products/'
    | '/ar/products/hi-tech_/$category'
    | '/ar/products/yokohama_/$category'
    | '/de/products/hi-tech_/$category'
    | '/de/products/yokohama_/$category'
    | '/fa/products/hi-tech_/$category'
    | '/fa/products/yokohama_/$category'
    | '/fr/products/hi-tech_/$category'
    | '/fr/products/yokohama_/$category'
    | '/products/hi-tech_/$category/$product'
    | '/products/yokohama_/$category/$product'
    | '/ru/products/hi-tech_/$category'
    | '/ru/products/yokohama_/$category'
    | '/tr/products/hi-tech_/$category'
    | '/tr/products/yokohama_/$category'
    | '/ar/products/hi-tech_/$category/$product'
    | '/ar/products/yokohama_/$category/$product'
    | '/de/products/hi-tech_/$category/$product'
    | '/de/products/yokohama_/$category/$product'
    | '/fa/products/hi-tech_/$category/$product'
    | '/fa/products/yokohama_/$category/$product'
    | '/fr/products/hi-tech_/$category/$product'
    | '/fr/products/yokohama_/$category/$product'
    | '/ru/products/hi-tech_/$category/$product'
    | '/ru/products/yokohama_/$category/$product'
    | '/tr/products/hi-tech_/$category/$product'
    | '/tr/products/yokohama_/$category/$product'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CatalogsRoute: typeof CatalogsRoute
  ContactRoute: typeof ContactRoute
  ExportRoute: typeof ExportRoute
  IndustriesRoute: typeof IndustriesRoute
  MediaRoute: typeof MediaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ArAboutRoute: typeof ArAboutRoute
  ArBlogRoute: typeof ArBlogRoute
  ArCatalogsRoute: typeof ArCatalogsRoute
  ArContactRoute: typeof ArContactRoute
  ArExportRoute: typeof ArExportRoute
  ArIndustriesRoute: typeof ArIndustriesRoute
  ArMediaRoute: typeof ArMediaRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DeAboutRoute: typeof DeAboutRoute
  DeBlogRoute: typeof DeBlogRoute
  DeCatalogsRoute: typeof DeCatalogsRoute
  DeContactRoute: typeof DeContactRoute
  DeExportRoute: typeof DeExportRoute
  DeIndustriesRoute: typeof DeIndustriesRoute
  DeMediaRoute: typeof DeMediaRoute
  FaAboutRoute: typeof FaAboutRoute
  FaBlogRoute: typeof FaBlogRoute
  FaCatalogsRoute: typeof FaCatalogsRoute
  FaContactRoute: typeof FaContactRoute
  FaExportRoute: typeof FaExportRoute
  FaIndustriesRoute: typeof FaIndustriesRoute
  FaMediaRoute: typeof FaMediaRoute
  FrAboutRoute: typeof FrAboutRoute
  FrBlogRoute: typeof FrBlogRoute
  FrCatalogsRoute: typeof FrCatalogsRoute
  FrContactRoute: typeof FrContactRoute
  FrExportRoute: typeof FrExportRoute
  FrIndustriesRoute: typeof FrIndustriesRoute
  FrMediaRoute: typeof FrMediaRoute
  ProductsHiTechRoute: typeof ProductsHiTechRoute
  ProductsYokohamaRoute: typeof ProductsYokohamaRoute
  RuAboutRoute: typeof RuAboutRoute
  RuBlogRoute: typeof RuBlogRoute
  RuCatalogsRoute: typeof RuCatalogsRoute
  RuContactRoute: typeof RuContactRoute
  RuExportRoute: typeof RuExportRoute
  RuIndustriesRoute: typeof RuIndustriesRoute
  RuMediaRoute: typeof RuMediaRoute
  TrAboutRoute: typeof TrAboutRoute
  TrBlogRoute: typeof TrBlogRoute
  TrCatalogsRoute: typeof TrCatalogsRoute
  TrContactRoute: typeof TrContactRoute
  TrExportRoute: typeof TrExportRoute
  TrIndustriesRoute: typeof TrIndustriesRoute
  TrMediaRoute: typeof TrMediaRoute
  ArIndexRoute: typeof ArIndexRoute
  DeIndexRoute: typeof DeIndexRoute
  FaIndexRoute: typeof FaIndexRoute
  FrIndexRoute: typeof FrIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  RuIndexRoute: typeof RuIndexRoute
  TrIndexRoute: typeof TrIndexRoute
  ArBlogSlugRoute: typeof ArBlogSlugRoute
  ArProductsHiTechRoute: typeof ArProductsHiTechRoute
  ArProductsYokohamaRoute: typeof ArProductsYokohamaRoute
  DeBlogSlugRoute: typeof DeBlogSlugRoute
  DeProductsHiTechRoute: typeof DeProductsHiTechRoute
  DeProductsYokohamaRoute: typeof DeProductsYokohamaRoute
  FaBlogSlugRoute: typeof FaBlogSlugRoute
  FaProductsHiTechRoute: typeof FaProductsHiTechRoute
  FaProductsYokohamaRoute: typeof FaProductsYokohamaRoute
  FrBlogSlugRoute: typeof FrBlogSlugRoute
  FrProductsHiTechRoute: typeof FrProductsHiTechRoute
  FrProductsYokohamaRoute: typeof FrProductsYokohamaRoute
  ProductsHiTechCategoryRoute: typeof ProductsHiTechCategoryRouteWithChildren
  ProductsYokohamaCategoryRoute: typeof ProductsYokohamaCategoryRouteWithChildren
  RuBlogSlugRoute: typeof RuBlogSlugRoute
  RuProductsHiTechRoute: typeof RuProductsHiTechRoute
  RuProductsYokohamaRoute: typeof RuProductsYokohamaRoute
  TrBlogSlugRoute: typeof TrBlogSlugRoute
  TrProductsHiTechRoute: typeof TrProductsHiTechRoute
  TrProductsYokohamaRoute: typeof TrProductsYokohamaRoute
  ArProductsIndexRoute: typeof ArProductsIndexRoute
  DeProductsIndexRoute: typeof DeProductsIndexRoute
  FaProductsIndexRoute: typeof FaProductsIndexRoute
  FrProductsIndexRoute: typeof FrProductsIndexRoute
  RuProductsIndexRoute: typeof RuProductsIndexRoute
  TrProductsIndexRoute: typeof TrProductsIndexRoute
  ArProductsHiTechCategoryRoute: typeof ArProductsHiTechCategoryRouteWithChildren
  ArProductsYokohamaCategoryRoute: typeof ArProductsYokohamaCategoryRouteWithChildren
  DeProductsHiTechCategoryRoute: typeof DeProductsHiTechCategoryRouteWithChildren
  DeProductsYokohamaCategoryRoute: typeof DeProductsYokohamaCategoryRouteWithChildren
  FaProductsHiTechCategoryRoute: typeof FaProductsHiTechCategoryRouteWithChildren
  FaProductsYokohamaCategoryRoute: typeof FaProductsYokohamaCategoryRouteWithChildren
  FrProductsHiTechCategoryRoute: typeof FrProductsHiTechCategoryRouteWithChildren
  FrProductsYokohamaCategoryRoute: typeof FrProductsYokohamaCategoryRouteWithChildren
  RuProductsHiTechCategoryRoute: typeof RuProductsHiTechCategoryRouteWithChildren
  RuProductsYokohamaCategoryRoute: typeof RuProductsYokohamaCategoryRouteWithChildren
  TrProductsHiTechCategoryRoute: typeof TrProductsHiTechCategoryRouteWithChildren
  TrProductsYokohamaCategoryRoute: typeof TrProductsYokohamaCategoryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogs': {
      id: '/catalogs'
      path: '/catalogs'
      fullPath: '/catalogs'
      preLoaderRoute: typeof CatalogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/': {
      id: '/tr/'
      path: '/tr'
      fullPath: '/tr/'
      preLoaderRoute: typeof TrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/': {
      id: '/ru/'
      path: '/ru'
      fullPath: '/ru/'
      preLoaderRoute: typeof RuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/': {
      id: '/fr/'
      path: '/fr'
      fullPath: '/fr/'
      preLoaderRoute: typeof FrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fa/': {
      id: '/fa/'
      path: '/fa'
      fullPath: '/fa/'
      preLoaderRoute: typeof FaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/': {
      id: '/de/'
      path: '/de'
      fullPath: '/de/'
      preLoaderRoute: typeof DeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/': {
      id: '/ar/'
      path: '/ar'
      fullPath: '/ar/'
      preLoaderRoute: typeof ArIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/media': {
      id: '/tr/media'
      path: '/tr/media'
      fullPath: '/tr/media'
      preLoaderRoute: typeof TrMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/industries': {
      id: '/tr/industries'
      path: '/tr/industries'
      fullPath: '/tr/industries'
      preLoaderRoute: typeof TrIndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/export': {
      id: '/tr/export'
      path: '/tr/export'
      fullPath: '/tr/export'
      preLoaderRoute: typeof TrExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/contact': {
      id: '/tr/contact'
      path: '/tr/contact'
      fullPath: '/tr/contact'
      preLoaderRoute: typeof TrContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/catalogs': {
      id: '/tr/catalogs'
      path: '/tr/catalogs'
      fullPath: '/tr/catalogs'
      preLoaderRoute: typeof TrCatalogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/blog': {
      id: '/tr/blog'
      path: '/tr/blog'
      fullPath: '/tr/blog'
      preLoaderRoute: typeof TrBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/about': {
      id: '/tr/about'
      path: '/tr/about'
      fullPath: '/tr/about'
      preLoaderRoute: typeof TrAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/media': {
      id: '/ru/media'
      path: '/ru/media'
      fullPath: '/ru/media'
      preLoaderRoute: typeof RuMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/industries': {
      id: '/ru/industries'
      path: '/ru/industries'
      fullPath: '/ru/industries'
      preLoaderRoute: typeof RuIndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/export': {
      id: '/ru/export'
      path: '/ru/export'
      fullPath: '/ru/export'
      preLoaderRoute: typeof RuExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/contact': {
      id: '/ru/contact'
      path: '/ru/contact'
      fullPath: '/ru/contact'
      preLoaderRoute: typeof RuContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/catalogs': {
      id: '/ru/catalogs'
      path: '/ru/catalogs'
      fullPath: '/ru/catalogs'
      preLoaderRoute: typeof RuCatalogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/blog': {
      id: '/ru/blog'
      path: '/ru/blog'
      fullPath: '/ru/blog'
      preLoaderRoute: typeof RuBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/about': {
      id: '/ru/about'
      path: '/ru/about'
      fullPath: '/ru/about'
      preLoaderRoute: typeof RuAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/yokohama': {
      id: '/products/yokohama'
      path: '/products/yokohama'
      fullPath: '/products/yokohama'
      preLoaderRoute: typeof ProductsYokohamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/hi-tech': {
      id: '/products/hi-tech'
      path: '/products/hi-tech'
      fullPath: '/products/hi-tech'
      preLoaderRoute: typeof ProductsHiTechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/media': {
      id: '/fr/media'
      path: '/fr/media'
      fullPath: '/fr/media'
      preLoaderRoute: typeof FrMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/industries': {
      id: '/fr/industries'
      path: '/fr/industries'
      fullPath: '/fr/industries'
      preLoaderRoute: typeof FrIndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/export': {
      id: '/fr/export'
      path: '/fr/export'
      fullPath: '/fr/export'
      preLoaderRoute: typeof FrExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/contact': {
      id: '/fr/contact'
      path: '/fr/contact'
      fullPath: '/fr/contact'
      preLoaderRoute: typeof FrContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/catalogs': {
      id: '/fr/catalogs'
      path: '/fr/catalogs'
      fullPath: '/fr/catalogs'
      preLoaderRoute: typeof FrCatalogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/blog': {
      id: '/fr/blog'
      path: '/fr/blog'
      fullPath: '/fr/blog'
      preLoaderRoute: typeof FrBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/about': {
      id: '/fr/about'
      path: '/fr/about'
      fullPath: '/fr/about'
      preLoaderRoute: typeof FrAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fa/media': {
      id: '/fa/media'
      path: '/fa/media'
      fullPath: '/fa/media'
      preLoaderRoute: typeof FaMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fa/industries': {
      id: '/fa/industries'
      path: '/fa/industries'
      fullPath: '/fa/industries'
      preLoaderRoute: typeof FaIndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fa/export': {
      id: '/fa/export'
      path: '/fa/export'
      fullPath: '/fa/export'
      preLoaderRoute: typeof FaExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fa/contact': {
      id: '/fa/contact'
      path: '/fa/contact'
      fullPath: '/fa/contact'
      preLoaderRoute: typeof FaContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fa/catalogs': {
      id: '/fa/catalogs'
      path: '/fa/catalogs'
      fullPath: '/fa/catalogs'
      preLoaderRoute: typeof FaCatalogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fa/blog': {
      id: '/fa/blog'
      path: '/fa/blog'
      fullPath: '/fa/blog'
      preLoaderRoute: typeof FaBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fa/about': {
      id: '/fa/about'
      path: '/fa/about'
      fullPath: '/fa/about'
      preLoaderRoute: typeof FaAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/media': {
      id: '/de/media'
      path: '/de/media'
      fullPath: '/de/media'
      preLoaderRoute: typeof DeMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/industries': {
      id: '/de/industries'
      path: '/de/industries'
      fullPath: '/de/industries'
      preLoaderRoute: typeof DeIndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/export': {
      id: '/de/export'
      path: '/de/export'
      fullPath: '/de/export'
      preLoaderRoute: typeof DeExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/contact': {
      id: '/de/contact'
      path: '/de/contact'
      fullPath: '/de/contact'
      preLoaderRoute: typeof DeContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/catalogs': {
      id: '/de/catalogs'
      path: '/de/catalogs'
      fullPath: '/de/catalogs'
      preLoaderRoute: typeof DeCatalogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/blog': {
      id: '/de/blog'
      path: '/de/blog'
      fullPath: '/de/blog'
      preLoaderRoute: typeof DeBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/about': {
      id: '/de/about'
      path: '/de/about'
      fullPath: '/de/about'
      preLoaderRoute: typeof DeAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/media': {
      id: '/ar/media'
      path: '/ar/media'
      fullPath: '/ar/media'
      preLoaderRoute: typeof ArMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/industries': {
      id: '/ar/industries'
      path: '/ar/industries'
      fullPath: '/ar/industries'
      preLoaderRoute: typeof ArIndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/export': {
      id: '/ar/export'
      path: '/ar/export'
      fullPath: '/ar/export'
      preLoaderRoute: typeof ArExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/contact': {
      id: '/ar/contact'
      path: '/ar/contact'
      fullPath: '/ar/contact'
      preLoaderRoute: typeof ArContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/catalogs': {
      id: '/ar/catalogs'
      path: '/ar/catalogs'
      fullPath: '/ar/catalogs'
      preLoaderRoute: typeof ArCatalogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/blog': {
      id: '/ar/blog'
      path: '/ar/blog'
      fullPath: '/ar/blog'
      preLoaderRoute: typeof ArBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/about': {
      id: '/ar/about'
      path: '/ar/about'
      fullPath: '/ar/about'
      preLoaderRoute: typeof ArAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/products/': {
      id: '/tr/products/'
      path: '/tr/products'
      fullPath: '/tr/products/'
      preLoaderRoute: typeof TrProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/products/': {
      id: '/ru/products/'
      path: '/ru/products'
      fullPath: '/ru/products/'
      preLoaderRoute: typeof RuProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/products/': {
      id: '/fr/products/'
      path: '/fr/products'
      fullPath: '/fr/products/'
      preLoaderRoute: typeof FrProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fa/products/': {
      id: '/fa/products/'
      path: '/fa/products'
      fullPath: '/fa/products/'
      preLoaderRoute: typeof FaProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/products/': {
      id: '/de/products/'
      path: '/de/products'
      fullPath: '/de/products/'
      preLoaderRoute: typeof DeProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/products/': {
      id: '/ar/products/'
      path: '/ar/products'
      fullPath: '/ar/products/'
      preLoaderRoute: typeof ArProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/products/yokohama': {
      id: '/tr/products/yokohama'
      path: '/tr/products/yokohama'
      fullPath: '/tr/products/yokohama'
      preLoaderRoute: typeof TrProductsYokohamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/products/hi-tech': {
      id: '/tr/products/hi-tech'
      path: '/tr/products/hi-tech'
      fullPath: '/tr/products/hi-tech'
      preLoaderRoute: typeof TrProductsHiTechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/blog_/$slug': {
      id: '/tr/blog_/$slug'
      path: '/tr/blog/$slug'
      fullPath: '/tr/blog/$slug'
      preLoaderRoute: typeof TrBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/products/yokohama': {
      id: '/ru/products/yokohama'
      path: '/ru/products/yokohama'
      fullPath: '/ru/products/yokohama'
      preLoaderRoute: typeof RuProductsYokohamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/products/hi-tech': {
      id: '/ru/products/hi-tech'
      path: '/ru/products/hi-tech'
      fullPath: '/ru/products/hi-tech'
      preLoaderRoute: typeof RuProductsHiTechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/blog_/$slug': {
      id: '/ru/blog_/$slug'
      path: '/ru/blog/$slug'
      fullPath: '/ru/blog/$slug'
      preLoaderRoute: typeof RuBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/yokohama_/$category': {
      id: '/products/yokohama_/$category'
      path: '/products/yokohama/$category'
      fullPath: '/products/yokohama/$category'
      preLoaderRoute: typeof ProductsYokohamaCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/hi-tech_/$category': {
      id: '/products/hi-tech_/$category'
      path: '/products/hi-tech/$category'
      fullPath: '/products/hi-tech/$category'
      preLoaderRoute: typeof ProductsHiTechCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/products/yokohama': {
      id: '/fr/products/yokohama'
      path: '/fr/products/yokohama'
      fullPath: '/fr/products/yokohama'
      preLoaderRoute: typeof FrProductsYokohamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/products/hi-tech': {
      id: '/fr/products/hi-tech'
      path: '/fr/products/hi-tech'
      fullPath: '/fr/products/hi-tech'
      preLoaderRoute: typeof FrProductsHiTechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/blog_/$slug': {
      id: '/fr/blog_/$slug'
      path: '/fr/blog/$slug'
      fullPath: '/fr/blog/$slug'
      preLoaderRoute: typeof FrBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fa/products/yokohama': {
      id: '/fa/products/yokohama'
      path: '/fa/products/yokohama'
      fullPath: '/fa/products/yokohama'
      preLoaderRoute: typeof FaProductsYokohamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fa/products/hi-tech': {
      id: '/fa/products/hi-tech'
      path: '/fa/products/hi-tech'
      fullPath: '/fa/products/hi-tech'
      preLoaderRoute: typeof FaProductsHiTechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fa/blog_/$slug': {
      id: '/fa/blog_/$slug'
      path: '/fa/blog/$slug'
      fullPath: '/fa/blog/$slug'
      preLoaderRoute: typeof FaBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/products/yokohama': {
      id: '/de/products/yokohama'
      path: '/de/products/yokohama'
      fullPath: '/de/products/yokohama'
      preLoaderRoute: typeof DeProductsYokohamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/products/hi-tech': {
      id: '/de/products/hi-tech'
      path: '/de/products/hi-tech'
      fullPath: '/de/products/hi-tech'
      preLoaderRoute: typeof DeProductsHiTechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/blog_/$slug': {
      id: '/de/blog_/$slug'
      path: '/de/blog/$slug'
      fullPath: '/de/blog/$slug'
      preLoaderRoute: typeof DeBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/products/yokohama': {
      id: '/ar/products/yokohama'
      path: '/ar/products/yokohama'
      fullPath: '/ar/products/yokohama'
      preLoaderRoute: typeof ArProductsYokohamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/products/hi-tech': {
      id: '/ar/products/hi-tech'
      path: '/ar/products/hi-tech'
      fullPath: '/ar/products/hi-tech'
      preLoaderRoute: typeof ArProductsHiTechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/blog_/$slug': {
      id: '/ar/blog_/$slug'
      path: '/ar/blog/$slug'
      fullPath: '/ar/blog/$slug'
      preLoaderRoute: typeof ArBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/products/yokohama_/$category': {
      id: '/tr/products/yokohama_/$category'
      path: '/tr/products/yokohama/$category'
      fullPath: '/tr/products/yokohama/$category'
      preLoaderRoute: typeof TrProductsYokohamaCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/products/hi-tech_/$category': {
      id: '/tr/products/hi-tech_/$category'
      path: '/tr/products/hi-tech/$category'
      fullPath: '/tr/products/hi-tech/$category'
      preLoaderRoute: typeof TrProductsHiTechCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/products/yokohama_/$category': {
      id: '/ru/products/yokohama_/$category'
      path: '/ru/products/yokohama/$category'
      fullPath: '/ru/products/yokohama/$category'
      preLoaderRoute: typeof RuProductsYokohamaCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/products/hi-tech_/$category': {
      id: '/ru/products/hi-tech_/$category'
      path: '/ru/products/hi-tech/$category'
      fullPath: '/ru/products/hi-tech/$category'
      preLoaderRoute: typeof RuProductsHiTechCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/yokohama_/$category/$product': {
      id: '/products/yokohama_/$category/$product'
      path: '/$product'
      fullPath: '/products/yokohama/$category/$product'
      preLoaderRoute: typeof ProductsYokohamaCategoryProductRouteImport
      parentRoute: typeof ProductsYokohamaCategoryRoute
    }
    '/products/hi-tech_/$category/$product': {
      id: '/products/hi-tech_/$category/$product'
      path: '/$product'
      fullPath: '/products/hi-tech/$category/$product'
      preLoaderRoute: typeof ProductsHiTechCategoryProductRouteImport
      parentRoute: typeof ProductsHiTechCategoryRoute
    }
    '/fr/products/yokohama_/$category': {
      id: '/fr/products/yokohama_/$category'
      path: '/fr/products/yokohama/$category'
      fullPath: '/fr/products/yokohama/$category'
      preLoaderRoute: typeof FrProductsYokohamaCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/products/hi-tech_/$category': {
      id: '/fr/products/hi-tech_/$category'
      path: '/fr/products/hi-tech/$category'
      fullPath: '/fr/products/hi-tech/$category'
      preLoaderRoute: typeof FrProductsHiTechCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fa/products/yokohama_/$category': {
      id: '/fa/products/yokohama_/$category'
      path: '/fa/products/yokohama/$category'
      fullPath: '/fa/products/yokohama/$category'
      preLoaderRoute: typeof FaProductsYokohamaCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fa/products/hi-tech_/$category': {
      id: '/fa/products/hi-tech_/$category'
      path: '/fa/products/hi-tech/$category'
      fullPath: '/fa/products/hi-tech/$category'
      preLoaderRoute: typeof FaProductsHiTechCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/products/yokohama_/$category': {
      id: '/de/products/yokohama_/$category'
      path: '/de/products/yokohama/$category'
      fullPath: '/de/products/yokohama/$category'
      preLoaderRoute: typeof DeProductsYokohamaCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/products/hi-tech_/$category': {
      id: '/de/products/hi-tech_/$category'
      path: '/de/products/hi-tech/$category'
      fullPath: '/de/products/hi-tech/$category'
      preLoaderRoute: typeof DeProductsHiTechCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/products/yokohama_/$category': {
      id: '/ar/products/yokohama_/$category'
      path: '/ar/products/yokohama/$category'
      fullPath: '/ar/products/yokohama/$category'
      preLoaderRoute: typeof ArProductsYokohamaCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/products/hi-tech_/$category': {
      id: '/ar/products/hi-tech_/$category'
      path: '/ar/products/hi-tech/$category'
      fullPath: '/ar/products/hi-tech/$category'
      preLoaderRoute: typeof ArProductsHiTechCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tr/products/yokohama_/$category/$product': {
      id: '/tr/products/yokohama_/$category/$product'
      path: '/$product'
      fullPath: '/tr/products/yokohama/$category/$product'
      preLoaderRoute: typeof TrProductsYokohamaCategoryProductRouteImport
      parentRoute: typeof TrProductsYokohamaCategoryRoute
    }
    '/tr/products/hi-tech_/$category/$product': {
      id: '/tr/products/hi-tech_/$category/$product'
      path: '/$product'
      fullPath: '/tr/products/hi-tech/$category/$product'
      preLoaderRoute: typeof TrProductsHiTechCategoryProductRouteImport
      parentRoute: typeof TrProductsHiTechCategoryRoute
    }
    '/ru/products/yokohama_/$category/$product': {
      id: '/ru/products/yokohama_/$category/$product'
      path: '/$product'
      fullPath: '/ru/products/yokohama/$category/$product'
      preLoaderRoute: typeof RuProductsYokohamaCategoryProductRouteImport
      parentRoute: typeof RuProductsYokohamaCategoryRoute
    }
    '/ru/products/hi-tech_/$category/$product': {
      id: '/ru/products/hi-tech_/$category/$product'
      path: '/$product'
      fullPath: '/ru/products/hi-tech/$category/$product'
      preLoaderRoute: typeof RuProductsHiTechCategoryProductRouteImport
      parentRoute: typeof RuProductsHiTechCategoryRoute
    }
    '/fr/products/yokohama_/$category/$product': {
      id: '/fr/products/yokohama_/$category/$product'
      path: '/$product'
      fullPath: '/fr/products/yokohama/$category/$product'
      preLoaderRoute: typeof FrProductsYokohamaCategoryProductRouteImport
      parentRoute: typeof FrProductsYokohamaCategoryRoute
    }
    '/fr/products/hi-tech_/$category/$product': {
      id: '/fr/products/hi-tech_/$category/$product'
      path: '/$product'
      fullPath: '/fr/products/hi-tech/$category/$product'
      preLoaderRoute: typeof FrProductsHiTechCategoryProductRouteImport
      parentRoute: typeof FrProductsHiTechCategoryRoute
    }
    '/fa/products/yokohama_/$category/$product': {
      id: '/fa/products/yokohama_/$category/$product'
      path: '/$product'
      fullPath: '/fa/products/yokohama/$category/$product'
      preLoaderRoute: typeof FaProductsYokohamaCategoryProductRouteImport
      parentRoute: typeof FaProductsYokohamaCategoryRoute
    }
    '/fa/products/hi-tech_/$category/$product': {
      id: '/fa/products/hi-tech_/$category/$product'
      path: '/$product'
      fullPath: '/fa/products/hi-tech/$category/$product'
      preLoaderRoute: typeof FaProductsHiTechCategoryProductRouteImport
      parentRoute: typeof FaProductsHiTechCategoryRoute
    }
    '/de/products/yokohama_/$category/$product': {
      id: '/de/products/yokohama_/$category/$product'
      path: '/$product'
      fullPath: '/de/products/yokohama/$category/$product'
      preLoaderRoute: typeof DeProductsYokohamaCategoryProductRouteImport
      parentRoute: typeof DeProductsYokohamaCategoryRoute
    }
    '/de/products/hi-tech_/$category/$product': {
      id: '/de/products/hi-tech_/$category/$product'
      path: '/$product'
      fullPath: '/de/products/hi-tech/$category/$product'
      preLoaderRoute: typeof DeProductsHiTechCategoryProductRouteImport
      parentRoute: typeof DeProductsHiTechCategoryRoute
    }
    '/ar/products/yokohama_/$category/$product': {
      id: '/ar/products/yokohama_/$category/$product'
      path: '/$product'
      fullPath: '/ar/products/yokohama/$category/$product'
      preLoaderRoute: typeof ArProductsYokohamaCategoryProductRouteImport
      parentRoute: typeof ArProductsYokohamaCategoryRoute
    }
    '/ar/products/hi-tech_/$category/$product': {
      id: '/ar/products/hi-tech_/$category/$product'
      path: '/$product'
      fullPath: '/ar/products/hi-tech/$category/$product'
      preLoaderRoute: typeof ArProductsHiTechCategoryProductRouteImport
      parentRoute: typeof ArProductsHiTechCategoryRoute
    }
  }
}

interface ProductsHiTechCategoryRouteChildren {
  ProductsHiTechCategoryProductRoute: typeof ProductsHiTechCategoryProductRoute
}

const ProductsHiTechCategoryRouteChildren: ProductsHiTechCategoryRouteChildren =
  {
    ProductsHiTechCategoryProductRoute: ProductsHiTechCategoryProductRoute,
  }

const ProductsHiTechCategoryRouteWithChildren =
  ProductsHiTechCategoryRoute._addFileChildren(
    ProductsHiTechCategoryRouteChildren,
  )

interface ProductsYokohamaCategoryRouteChildren {
  ProductsYokohamaCategoryProductRoute: typeof ProductsYokohamaCategoryProductRoute
}

const ProductsYokohamaCategoryRouteChildren: ProductsYokohamaCategoryRouteChildren =
  {
    ProductsYokohamaCategoryProductRoute: ProductsYokohamaCategoryProductRoute,
  }

const ProductsYokohamaCategoryRouteWithChildren =
  ProductsYokohamaCategoryRoute._addFileChildren(
    ProductsYokohamaCategoryRouteChildren,
  )

interface ArProductsHiTechCategoryRouteChildren {
  ArProductsHiTechCategoryProductRoute: typeof ArProductsHiTechCategoryProductRoute
}

const ArProductsHiTechCategoryRouteChildren: ArProductsHiTechCategoryRouteChildren =
  {
    ArProductsHiTechCategoryProductRoute: ArProductsHiTechCategoryProductRoute,
  }

const ArProductsHiTechCategoryRouteWithChildren =
  ArProductsHiTechCategoryRoute._addFileChildren(
    ArProductsHiTechCategoryRouteChildren,
  )

interface ArProductsYokohamaCategoryRouteChildren {
  ArProductsYokohamaCategoryProductRoute: typeof ArProductsYokohamaCategoryProductRoute
}

const ArProductsYokohamaCategoryRouteChildren: ArProductsYokohamaCategoryRouteChildren =
  {
    ArProductsYokohamaCategoryProductRoute:
      ArProductsYokohamaCategoryProductRoute,
  }

const ArProductsYokohamaCategoryRouteWithChildren =
  ArProductsYokohamaCategoryRoute._addFileChildren(
    ArProductsYokohamaCategoryRouteChildren,
  )

interface DeProductsHiTechCategoryRouteChildren {
  DeProductsHiTechCategoryProductRoute: typeof DeProductsHiTechCategoryProductRoute
}

const DeProductsHiTechCategoryRouteChildren: DeProductsHiTechCategoryRouteChildren =
  {
    DeProductsHiTechCategoryProductRoute: DeProductsHiTechCategoryProductRoute,
  }

const DeProductsHiTechCategoryRouteWithChildren =
  DeProductsHiTechCategoryRoute._addFileChildren(
    DeProductsHiTechCategoryRouteChildren,
  )

interface DeProductsYokohamaCategoryRouteChildren {
  DeProductsYokohamaCategoryProductRoute: typeof DeProductsYokohamaCategoryProductRoute
}

const DeProductsYokohamaCategoryRouteChildren: DeProductsYokohamaCategoryRouteChildren =
  {
    DeProductsYokohamaCategoryProductRoute:
      DeProductsYokohamaCategoryProductRoute,
  }

const DeProductsYokohamaCategoryRouteWithChildren =
  DeProductsYokohamaCategoryRoute._addFileChildren(
    DeProductsYokohamaCategoryRouteChildren,
  )

interface FaProductsHiTechCategoryRouteChildren {
  FaProductsHiTechCategoryProductRoute: typeof FaProductsHiTechCategoryProductRoute
}

const FaProductsHiTechCategoryRouteChildren: FaProductsHiTechCategoryRouteChildren =
  {
    FaProductsHiTechCategoryProductRoute: FaProductsHiTechCategoryProductRoute,
  }

const FaProductsHiTechCategoryRouteWithChildren =
  FaProductsHiTechCategoryRoute._addFileChildren(
    FaProductsHiTechCategoryRouteChildren,
  )

interface FaProductsYokohamaCategoryRouteChildren {
  FaProductsYokohamaCategoryProductRoute: typeof FaProductsYokohamaCategoryProductRoute
}

const FaProductsYokohamaCategoryRouteChildren: FaProductsYokohamaCategoryRouteChildren =
  {
    FaProductsYokohamaCategoryProductRoute:
      FaProductsYokohamaCategoryProductRoute,
  }

const FaProductsYokohamaCategoryRouteWithChildren =
  FaProductsYokohamaCategoryRoute._addFileChildren(
    FaProductsYokohamaCategoryRouteChildren,
  )

interface FrProductsHiTechCategoryRouteChildren {
  FrProductsHiTechCategoryProductRoute: typeof FrProductsHiTechCategoryProductRoute
}

const FrProductsHiTechCategoryRouteChildren: FrProductsHiTechCategoryRouteChildren =
  {
    FrProductsHiTechCategoryProductRoute: FrProductsHiTechCategoryProductRoute,
  }

const FrProductsHiTechCategoryRouteWithChildren =
  FrProductsHiTechCategoryRoute._addFileChildren(
    FrProductsHiTechCategoryRouteChildren,
  )

interface FrProductsYokohamaCategoryRouteChildren {
  FrProductsYokohamaCategoryProductRoute: typeof FrProductsYokohamaCategoryProductRoute
}

const FrProductsYokohamaCategoryRouteChildren: FrProductsYokohamaCategoryRouteChildren =
  {
    FrProductsYokohamaCategoryProductRoute:
      FrProductsYokohamaCategoryProductRoute,
  }

const FrProductsYokohamaCategoryRouteWithChildren =
  FrProductsYokohamaCategoryRoute._addFileChildren(
    FrProductsYokohamaCategoryRouteChildren,
  )

interface RuProductsHiTechCategoryRouteChildren {
  RuProductsHiTechCategoryProductRoute: typeof RuProductsHiTechCategoryProductRoute
}

const RuProductsHiTechCategoryRouteChildren: RuProductsHiTechCategoryRouteChildren =
  {
    RuProductsHiTechCategoryProductRoute: RuProductsHiTechCategoryProductRoute,
  }

const RuProductsHiTechCategoryRouteWithChildren =
  RuProductsHiTechCategoryRoute._addFileChildren(
    RuProductsHiTechCategoryRouteChildren,
  )

interface RuProductsYokohamaCategoryRouteChildren {
  RuProductsYokohamaCategoryProductRoute: typeof RuProductsYokohamaCategoryProductRoute
}

const RuProductsYokohamaCategoryRouteChildren: RuProductsYokohamaCategoryRouteChildren =
  {
    RuProductsYokohamaCategoryProductRoute:
      RuProductsYokohamaCategoryProductRoute,
  }

const RuProductsYokohamaCategoryRouteWithChildren =
  RuProductsYokohamaCategoryRoute._addFileChildren(
    RuProductsYokohamaCategoryRouteChildren,
  )

interface TrProductsHiTechCategoryRouteChildren {
  TrProductsHiTechCategoryProductRoute: typeof TrProductsHiTechCategoryProductRoute
}

const TrProductsHiTechCategoryRouteChildren: TrProductsHiTechCategoryRouteChildren =
  {
    TrProductsHiTechCategoryProductRoute: TrProductsHiTechCategoryProductRoute,
  }

const TrProductsHiTechCategoryRouteWithChildren =
  TrProductsHiTechCategoryRoute._addFileChildren(
    TrProductsHiTechCategoryRouteChildren,
  )

interface TrProductsYokohamaCategoryRouteChildren {
  TrProductsYokohamaCategoryProductRoute: typeof TrProductsYokohamaCategoryProductRoute
}

const TrProductsYokohamaCategoryRouteChildren: TrProductsYokohamaCategoryRouteChildren =
  {
    TrProductsYokohamaCategoryProductRoute:
      TrProductsYokohamaCategoryProductRoute,
  }

const TrProductsYokohamaCategoryRouteWithChildren =
  TrProductsYokohamaCategoryRoute._addFileChildren(
    TrProductsYokohamaCategoryRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CatalogsRoute: CatalogsRoute,
  ContactRoute: ContactRoute,
  ExportRoute: ExportRoute,
  IndustriesRoute: IndustriesRoute,
  MediaRoute: MediaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ArAboutRoute: ArAboutRoute,
  ArBlogRoute: ArBlogRoute,
  ArCatalogsRoute: ArCatalogsRoute,
  ArContactRoute: ArContactRoute,
  ArExportRoute: ArExportRoute,
  ArIndustriesRoute: ArIndustriesRoute,
  ArMediaRoute: ArMediaRoute,
  BlogSlugRoute: BlogSlugRoute,
  DeAboutRoute: DeAboutRoute,
  DeBlogRoute: DeBlogRoute,
  DeCatalogsRoute: DeCatalogsRoute,
  DeContactRoute: DeContactRoute,
  DeExportRoute: DeExportRoute,
  DeIndustriesRoute: DeIndustriesRoute,
  DeMediaRoute: DeMediaRoute,
  FaAboutRoute: FaAboutRoute,
  FaBlogRoute: FaBlogRoute,
  FaCatalogsRoute: FaCatalogsRoute,
  FaContactRoute: FaContactRoute,
  FaExportRoute: FaExportRoute,
  FaIndustriesRoute: FaIndustriesRoute,
  FaMediaRoute: FaMediaRoute,
  FrAboutRoute: FrAboutRoute,
  FrBlogRoute: FrBlogRoute,
  FrCatalogsRoute: FrCatalogsRoute,
  FrContactRoute: FrContactRoute,
  FrExportRoute: FrExportRoute,
  FrIndustriesRoute: FrIndustriesRoute,
  FrMediaRoute: FrMediaRoute,
  ProductsHiTechRoute: ProductsHiTechRoute,
  ProductsYokohamaRoute: ProductsYokohamaRoute,
  RuAboutRoute: RuAboutRoute,
  RuBlogRoute: RuBlogRoute,
  RuCatalogsRoute: RuCatalogsRoute,
  RuContactRoute: RuContactRoute,
  RuExportRoute: RuExportRoute,
  RuIndustriesRoute: RuIndustriesRoute,
  RuMediaRoute: RuMediaRoute,
  TrAboutRoute: TrAboutRoute,
  TrBlogRoute: TrBlogRoute,
  TrCatalogsRoute: TrCatalogsRoute,
  TrContactRoute: TrContactRoute,
  TrExportRoute: TrExportRoute,
  TrIndustriesRoute: TrIndustriesRoute,
  TrMediaRoute: TrMediaRoute,
  ArIndexRoute: ArIndexRoute,
  DeIndexRoute: DeIndexRoute,
  FaIndexRoute: FaIndexRoute,
  FrIndexRoute: FrIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  RuIndexRoute: RuIndexRoute,
  TrIndexRoute: TrIndexRoute,
  ArBlogSlugRoute: ArBlogSlugRoute,
  ArProductsHiTechRoute: ArProductsHiTechRoute,
  ArProductsYokohamaRoute: ArProductsYokohamaRoute,
  DeBlogSlugRoute: DeBlogSlugRoute,
  DeProductsHiTechRoute: DeProductsHiTechRoute,
  DeProductsYokohamaRoute: DeProductsYokohamaRoute,
  FaBlogSlugRoute: FaBlogSlugRoute,
  FaProductsHiTechRoute: FaProductsHiTechRoute,
  FaProductsYokohamaRoute: FaProductsYokohamaRoute,
  FrBlogSlugRoute: FrBlogSlugRoute,
  FrProductsHiTechRoute: FrProductsHiTechRoute,
  FrProductsYokohamaRoute: FrProductsYokohamaRoute,
  ProductsHiTechCategoryRoute: ProductsHiTechCategoryRouteWithChildren,
  ProductsYokohamaCategoryRoute: ProductsYokohamaCategoryRouteWithChildren,
  RuBlogSlugRoute: RuBlogSlugRoute,
  RuProductsHiTechRoute: RuProductsHiTechRoute,
  RuProductsYokohamaRoute: RuProductsYokohamaRoute,
  TrBlogSlugRoute: TrBlogSlugRoute,
  TrProductsHiTechRoute: TrProductsHiTechRoute,
  TrProductsYokohamaRoute: TrProductsYokohamaRoute,
  ArProductsIndexRoute: ArProductsIndexRoute,
  DeProductsIndexRoute: DeProductsIndexRoute,
  FaProductsIndexRoute: FaProductsIndexRoute,
  FrProductsIndexRoute: FrProductsIndexRoute,
  RuProductsIndexRoute: RuProductsIndexRoute,
  TrProductsIndexRoute: TrProductsIndexRoute,
  ArProductsHiTechCategoryRoute: ArProductsHiTechCategoryRouteWithChildren,
  ArProductsYokohamaCategoryRoute: ArProductsYokohamaCategoryRouteWithChildren,
  DeProductsHiTechCategoryRoute: DeProductsHiTechCategoryRouteWithChildren,
  DeProductsYokohamaCategoryRoute: DeProductsYokohamaCategoryRouteWithChildren,
  FaProductsHiTechCategoryRoute: FaProductsHiTechCategoryRouteWithChildren,
  FaProductsYokohamaCategoryRoute: FaProductsYokohamaCategoryRouteWithChildren,
  FrProductsHiTechCategoryRoute: FrProductsHiTechCategoryRouteWithChildren,
  FrProductsYokohamaCategoryRoute: FrProductsYokohamaCategoryRouteWithChildren,
  RuProductsHiTechCategoryRoute: RuProductsHiTechCategoryRouteWithChildren,
  RuProductsYokohamaCategoryRoute: RuProductsYokohamaCategoryRouteWithChildren,
  TrProductsHiTechCategoryRoute: TrProductsHiTechCategoryRouteWithChildren,
  TrProductsYokohamaCategoryRoute: TrProductsYokohamaCategoryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
